import Link from "next/link";
import { ArrowRight, Award, CheckCircle2, FilePenLine, SearchCheck, Send, ShieldCheck, UsersRound } from "lucide-react";
import { DashboardPageHeader } from "@/app/dashboard/DashboardPageHeader";
import { GRADE_ITEM_STATUS_LABELS, GRADE_ITEM_TYPE_LABELS, GRADE_REVIEW_STATUS_LABELS, gradeDateFormatter, type GradeItemStatus, type GradeItemType, type GradeReviewStatus } from "@/app/dashboard/grades/config";
import { requireGradeCenterManager } from "@/lib/grade-center";
import { AssignmentGradeImportForm } from "./AssignmentGradeImportForm";
import { GradeCenterAdminManager } from "./GradeCenterAdminManager";
import { GradeItemForm } from "./GradeItemForm";
import { GradeItemStatusActions } from "./GradeItemStatusActions";
import { GradeReviewManager } from "./GradeReviewManager";

type Item = { id: string; title: string; description: string; item_type: GradeItemType; term: string; total_points: number; weight_percent: number; status: GradeItemStatus; source_assignment_id: string | null; updated_at: string };
type RecordRow = { id: string; item_id: string; student_id: string; score: number | null };
type Review = { id: string; record_id: string; student_id: string; reason: string; status: GradeReviewStatus; response: string; requested_at: string };
type Profile = { id: string; full_name: string | null; email: string | null };
export default async function GradeManagementPage() {
  const { supabase, canAssignAdmins, role } = await requireGradeCenterManager();
  const [itemsResult, recordsResult, reviewsResult, assignmentsResult] = await Promise.all([supabase.from("grade_items").select("id,title,description,item_type,term,total_points,weight_percent,status,source_assignment_id,updated_at").order("updated_at", { ascending: false }), supabase.from("grade_records").select("id,item_id,student_id,score"), supabase.from("grade_review_requests").select("id,record_id,student_id,reason,status,response,requested_at").order("requested_at", { ascending: false }), supabase.from("learning_assignments").select("id,title").order("created_at", { ascending: false })]);
  const items = (itemsResult.data ?? []) as Item[]; const records = (recordsResult.data ?? []) as RecordRow[]; const reviews = (reviewsResult.data ?? []) as Review[]; const recordMap = new Map(records.map((record) => [record.id, record]));
  const studentIds = [...new Set([...records.map((item) => item.student_id), ...reviews.map((item) => item.student_id)])]; const { data: studentData } = studentIds.length ? await supabase.from("profiles").select("id,full_name,email").in("id", studentIds) : { data: [] as Profile[] }; const names = new Map(((studentData ?? []) as Profile[]).map((item) => [item.id, item.full_name?.trim() || item.email || "学生"]));
  let admins: Array<{ id: string; name: string; email: string; assigned: boolean }> = []; if (canAssignAdmins) { const [{ data: adminData }, { data: assignedData }] = await Promise.all([supabase.from("profiles").select("id,full_name,email").eq("role", "admin").eq("status", "active").order("full_name", { ascending: true }), supabase.from("grade_center_admin_assignments").select("admin_id").is("revoked_at", null)]); const assigned = new Set((assignedData ?? []).map((item) => item.admin_id as string)); admins = ((adminData ?? []) as Profile[]).map((item) => ({ id: item.id, name: item.full_name?.trim() || "未填写姓名", email: item.email || "未填写邮箱", assigned: assigned.has(item.id) })); }
  const itemById = new Map(items.map((item) => [item.id, item])); const published = items.filter((item) => item.status === "published").length; const pendingReviews = reviews.filter((item) => item.status === "pending" || item.status === "reviewing").length;
  return <div className="pb-12"><DashboardPageHeader title="成绩管理" description="建立成绩项目、录入学生分数、发布成绩并处理复核。" action={<Link href="#create-grade-item" className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black text-white" style={{ backgroundColor: "var(--app-accent)" }}><FilePenLine size={15} />新建成绩项目</Link>} /><div className="mx-auto mt-6 w-full max-w-[1550px] space-y-6 px-4 sm:px-6 lg:px-8"><section className="app-card rounded-[30px] border p-6 sm:p-8" style={{ background: "linear-gradient(125deg, var(--app-card-bg), var(--app-hero-start), var(--app-secondary-soft))" }}><div className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_500px] xl:items-end"><div><span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-black" style={{ color: "var(--app-secondary)", backgroundColor: "var(--app-secondary-soft)" }}><ShieldCheck size={14} />{role === "super_admin" ? "负责人权限" : role === "ceo" ? "运营负责人权限" : "已授权管理员"}</span><h1 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">从批改到发布，再到复核闭环</h1><p className="app-muted-text mt-4 text-sm leading-7">草稿成绩不会出现在学生端；发布后学生可查看分数、评语并申请复核。</p></div><div className="grid grid-cols-3 gap-3">{[["已发布项目", published, Send, "var(--app-success)", "var(--app-success-soft)"], ["成绩记录", records.length, UsersRound, "var(--app-accent)", "var(--app-accent-soft)"], ["复核处理中", pendingReviews, SearchCheck, "var(--app-warm)", "var(--app-warm-soft)" ]].map(([label, value, Icon, color, soft]) => { const MetricIcon = Icon as typeof Award; return <div key={String(label)} className="app-card rounded-2xl border p-4 text-center"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-xl" style={{ color: String(color), backgroundColor: String(soft) }}><MetricIcon size={17} /></span><p className="mt-2 text-2xl font-black">{String(value)}</p><p className="app-muted-text text-[10px] font-black">{String(label)}</p></div>; })}</div></div></section>
  {(itemsResult.error || recordsResult.error || reviewsResult.error) && <section className="rounded-2xl border p-4 text-sm font-bold" style={{ color: "var(--app-warm)", backgroundColor: "var(--app-warm-soft)" }}>成绩后台数据暂时无法读取，请确认数据库迁移已经执行。</section>}
  <div className="grid items-start gap-6 xl:grid-cols-[minmax(360px,0.72fr)_minmax(0,1.35fr)]"><div className="space-y-6"><section id="create-grade-item" className="app-card rounded-[28px] border p-5 sm:p-7"><h2 className="text-lg font-black">新建成绩项目</h2><div className="mt-5"><GradeItemForm /></div></section><AssignmentGradeImportForm assignments={(assignmentsResult.data ?? []) as Array<{ id: string; title: string }>} />{canAssignAdmins && <GradeCenterAdminManager admins={admins} />}</div><div className="space-y-6"><section className="app-card rounded-[28px] border p-5 sm:p-7"><h2 className="text-xl font-black">成绩项目</h2><p className="app-muted-text mt-1 text-xs">共 {items.length} 个项目</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{items.map((item) => { const itemRecords = records.filter((record) => record.item_id === item.id); return <article key={item.id} className="app-soft-card rounded-2xl border p-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full px-2 py-1 text-[9px] font-black" style={{ color: "var(--app-secondary)", backgroundColor: "var(--app-secondary-soft)" }}>{GRADE_ITEM_TYPE_LABELS[item.item_type]}</span><span className="rounded-full px-2 py-1 text-[9px] font-black" style={{ color: item.status === "published" ? "var(--app-success)" : "var(--app-muted)", backgroundColor: item.status === "published" ? "var(--app-success-soft)" : "var(--app-soft-bg)" }}>{GRADE_ITEM_STATUS_LABELS[item.status]}</span>{item.source_assignment_id && <span className="text-[9px] font-black" style={{ color: "var(--app-accent)" }}>作业同步</span>}</div><h3 className="mt-3 text-base font-black">{item.title}</h3><p className="app-muted-text mt-2 text-xs">满分 {item.total_points} · 已录入 {itemRecords.length} 人{item.weight_percent > 0 ? ` · 权重 ${item.weight_percent}%` : ""}</p><div className="mt-4 space-y-3 border-t pt-4" style={{ borderColor: "var(--app-border-soft)" }}><GradeItemStatusActions id={item.id} status={item.status} /><Link href={`/dashboard/admin/grades/${item.id}`} className="inline-flex items-center gap-1.5 rounded-xl px-4 py-2.5 text-xs font-black text-white" style={{ backgroundColor: "var(--app-secondary)" }}>录入与管理<ArrowRight size={13} /></Link></div></article>; })}{items.length === 0 && <p className="app-muted-text col-span-full rounded-2xl border border-dashed p-8 text-center text-xs">还没有成绩项目。</p>}</div></section>
  <section className="app-card rounded-[28px] border p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-black"><SearchCheck size={19} style={{ color: "var(--app-warm)" }} />成绩复核申请</h2><p className="app-muted-text mt-1 text-xs">共 {reviews.length} 条申请</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{reviews.map((review) => { const record = recordMap.get(review.record_id); const item = record ? itemById.get(record.item_id) : undefined; return <article key={review.id} className="app-soft-card rounded-2xl border p-4"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-black">{names.get(review.student_id) || "学生"}</p><p className="app-muted-text mt-1 text-[10px]">{item?.title || "成绩项目"} · {GRADE_REVIEW_STATUS_LABELS[review.status]}</p></div>{review.status === "resolved" && <CheckCircle2 size={18} style={{ color: "var(--app-success)" }} />}</div><p className="app-muted-text mt-3 whitespace-pre-wrap text-xs leading-6">申请原因：{review.reason}</p><p className="app-muted-text mt-2 text-[9px]">{gradeDateFormatter.format(new Date(review.requested_at))}</p><div className="mt-4 border-t pt-4" style={{ borderColor: "var(--app-border-soft)" }}><GradeReviewManager reviewId={review.id} response={review.response} /></div></article>; })}{reviews.length === 0 && <p className="app-muted-text col-span-full rounded-2xl border border-dashed p-8 text-center text-xs">当前没有成绩复核申请。</p>}</div></section></div></div>
  </div></div>;
}
