"use server";
import { revalidatePath } from "next/cache";
import { requireLearningRecordManager } from "@/lib/learning-records";
import type { LearningRecordActionState } from "./action-state";
import { LEARNING_RECORD_TYPES, LEARNING_RECORD_VISIBILITIES, type LearningRecordType, type LearningRecordVisibility } from "./config";
function result(status: "success" | "error", message: string): LearningRecordActionState { return { status, message }; }
function isUuid(value: string) { return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }
function refreshRecords() { revalidatePath("/dashboard/records"); revalidatePath("/dashboard/admin/records"); revalidatePath("/dashboard/admin"); }
function readNote(formData: FormData) { const studentId = String(formData.get("student_id") ?? ""); const recordType = String(formData.get("record_type") ?? "coaching"); const title = String(formData.get("title") ?? "").trim(); const content = String(formData.get("content") ?? "").trim(); const nextAction = String(formData.get("next_action") ?? "").trim(); const visibility = String(formData.get("visibility") ?? "student_visible"); const occurredText = String(formData.get("occurred_at") ?? ""); const occurredAt = occurredText ? new Date(occurredText) : new Date(); if (!isUuid(studentId)) return { error: "请选择学生账号。" } as const; if (!(LEARNING_RECORD_TYPES as readonly string[]).includes(recordType)) return { error: "请选择有效的记录类型。" } as const; if (!(LEARNING_RECORD_VISIBILITIES as readonly string[]).includes(visibility)) return { error: "请选择有效的可见范围。" } as const; if (title.length < 2 || title.length > 120) return { error: "记录标题需要填写 2 至 120 个字。" } as const; if (content.length < 2 || content.length > 5000) return { error: "记录内容需要填写 2 至 5000 个字。" } as const; if (nextAction.length > 2000) return { error: "下一步建议不能超过 2000 个字。" } as const; if (Number.isNaN(occurredAt.getTime())) return { error: "记录时间不正确。" } as const; return { data: { p_student_id: studentId, p_record_type: recordType as LearningRecordType, p_title: title, p_content: content, p_next_action: nextAction, p_visibility: visibility as LearningRecordVisibility, p_occurred_at: occurredAt.toISOString() } } as const; }
export async function createLearningRecordNoteAction(_state: LearningRecordActionState, formData: FormData): Promise<LearningRecordActionState> { void _state; const { supabase } = await requireLearningRecordManager(); const input = readNote(formData); if ("error" in input && input.error) return result("error", input.error); const { error } = await supabase.rpc("save_learning_record_note", { p_id: null, ...input.data }); if (error) return result("error", "学习记录保存失败。"); refreshRecords(); return result("success", input.data.p_visibility === "student_visible" ? "学习记录已保存并同步到学生端。" : "后台内部记录已经保存。"); }
export async function updateLearningRecordNoteAction(noteId: string, _state: LearningRecordActionState, formData: FormData): Promise<LearningRecordActionState> { void _state; if (!isUuid(noteId)) return result("error", "学习记录编号不正确。"); const { supabase } = await requireLearningRecordManager(); const input = readNote(formData); if ("error" in input && input.error) return result("error", input.error); const { error } = await supabase.rpc("save_learning_record_note", { p_id: noteId, ...input.data }); if (error) return result("error", "学习记录修改失败。"); refreshRecords(); return result("success", "学习记录已经更新。"); }
export async function changeLearningRecordNoteStatusAction(noteId: string, nextStatus: "active" | "archived", _state: LearningRecordActionState, _formData: FormData): Promise<LearningRecordActionState> { void _state; void _formData; if (!isUuid(noteId)) return result("error", "学习记录编号不正确。"); const { supabase } = await requireLearningRecordManager(); const { error } = await supabase.rpc("change_learning_record_note_status", { p_note_id: noteId, p_status: nextStatus }); if (error) return result("error", "学习记录状态更新失败。"); refreshRecords(); return result("success", nextStatus === "archived" ? "学习记录已经归档。" : "学习记录已经恢复。"); }
