import Link from "next/link";
import { ArrowRight, Award, BookOpenCheck, CheckCircle2, Eye, History, MessageCircleMore, NotebookPen, Send, Sparkles } from "lucide-react";
import { getLearningRecordAccess } from "@/lib/learning-records";
import { LEARNING_RECORD_TYPE_LABELS, learningRecordDateFormatter, type LearningRecordType } from "./config";

export const runtime = "edge";
type Progress = { lesson_id:string; course_id:string; status:string; progress_percent:number|null; completed_at:string|null; last_viewed_at:string|null };
type Submission = { assignment_id:string; status:string; submitted_at:string; graded_at:string|null; score:number|null };
type Conversation = { scenario_id:string; status:string; practice_count:number; last_practiced_at:string };
type Grade = { item_id:string; record_status:string; score:number|null; graded_at:string };
type Note = { id:string; record_type:LearningRecordType; title:string; content:string; next_action:string; occurred_at:string };
type Named = { id:string; title:string; total_points?:number };
type Event = { id:string; type:"lesson"|"assignment"|"conversation"|"grade"|"note"; title:string; description:string; date:string; meta?:string; noteType?:LearningRecordType; nextAction?:string };
const eventStyle = { lesson:{icon:BookOpenCheck,color:"var(--app-accent)",soft:"var(--app-accent-soft)",label:"课程学习"}, assignment:{icon:Send,color:"var(--app-secondary)",soft:"var(--app-secondary-soft)",label:"作业考试"}, conversation:{icon:MessageCircleMore,color:"var(--app-success)",soft:"var(--app-success-soft)",label:"会话练习"}, grade:{icon:Award,color:"var(--app-warm)",soft:"var(--app-warm-soft)",label:"成绩记录"}, note:{icon:NotebookPen,color:"var(--app-secondary)",soft:"var(--app-secondary-soft)",label:"成长记录"} } as const;
export default async function LearningRecordsPage(){ const {supabase,user,role,canManage}=await getLearningRecordAccess(); const student=role==="student"; const [progressResult,submissionResult,conversationResult,gradeResult,noteResult]=await Promise.all([student?supabase.from("lesson_progress").select("lesson_id,course_id,status,progress_percent,completed_at,last_viewed_at").eq("user_id",user.id):Promise.resolve({data:[] as Progress[],error:null}),student?supabase.from("learning_submissions").select("assignment_id,status,submitted_at,graded_at,score").eq("student_id",user.id):Promise.resolve({data:[] as Submission[],error:null}),student?supabase.from("conversation_practice_progress").select("scenario_id,status,practice_count,last_practiced_at").eq("user_id",user.id):Promise.resolve({data:[] as Conversation[],error:null}),student?supabase.from("grade_records").select("item_id,record_status,score,graded_at").eq("student_id",user.id):Promise.resolve({data:[] as Grade[],error:null}),student?supabase.from("learning_record_notes").select("id,record_type,title,content,next_action,occurred_at").eq("student_id",user.id).eq("status","active").eq("visibility","student_visible"):Promise.resolve({data:[] as Note[],error:null})]);
  const progress=(progressResult.data??[]) as Progress[], submissions=(submissionResult.data??[]) as Submission[], conversations=(conversationResult.data??[]) as Conversation[], grades=(gradeResult.data??[]) as Grade[], notes=(noteResult.data??[]) as Note[];
  const lessonIds=[...new Set(progress.map(x=>x.lesson_id))], assignmentIds=[...new Set(submissions.map(x=>x.assignment_id))], scenarioIds=[...new Set(conversations.map(x=>x.scenario_id))], itemIds=[...new Set(grades.map(x=>x.item_id))];
  const [lessonNames,assignmentNames,scenarioNames,itemNames]=await Promise.all([lessonIds.length?supabase.from("lessons").select("id,title").in("id",lessonIds):Promise.resolve({data:[] as Named[]}),assignmentIds.length?supabase.from("learning_assignments").select("id,title").in("id",assignmentIds):Promise.resolve({data:[] as Named[]}),scenarioIds.length?supabase.from("conversation_practice_scenarios").select("id,title").in("id",scenarioIds):Promise.resolve({data:[] as Named[]}),itemIds.length?supabase.from("grade_items").select("id,title,total_points").in("id",itemIds):Promise.resolve({data:[] as Named[]})]);
  const map=(rows:unknown)=>new Map(((rows??[]) as Named[]).map(x=>[x.id,x])); const lm=map(lessonNames.data),am=map(assignmentNames.data),sm=map(scenarioNames.data),gm=map(itemNames.data); const events:Event[]=[];
  progress.forEach(x=>{const date=x.completed_at||x.last_viewed_at;if(date)events.push({id:`lesson-${x.lesson_id}-${date}`,type:"lesson",title:lm.get(x.lesson_id)?.title||"课程课时",description:x.status==="completed"?"完成了一个课程课时":`学习进度更新到 ${x.progress_percent??0}%`,date,meta:x.status==="completed"?"已完成":"学习中"});});
  submissions.forEach((x,i)=>events.push({id:`submission-${x.assignment_id}-${i}`,type:"assignment",title:am.get(x.assignment_id)?.title||"作业考试",description:x.status==="graded"?`成绩已发布：${x.score??0} 分`:x.status==="revision_required"?"老师要求修改后重新提交":"已提交，等待批改",date:x.graded_at||x.submitted_at,meta:x.status==="graded"?"已批改":"已提交"}));
  conversations.forEach(x=>events.push({id:`conversation-${x.scenario_id}`,type:"conversation",title:sm.get(x.scenario_id)?.title||"会话练习",description:`累计练习 ${x.practice_count} 次${x.status==="completed"?"，已经标记为掌握":""}`,date:x.last_practiced_at,meta:x.status==="completed"?"已掌握":"练习中"}));
  grades.forEach((x,i)=>{const item=gm.get(x.item_id);events.push({id:`grade-${x.item_id}-${i}`,type:"grade",title:item?.title||"成绩项目",description:x.record_status==="graded"?`获得 ${x.score??0} / ${item?.total_points??"—"} 分`:x.record_status==="absent"?"记录为缺考":"记录为免考",date:x.graded_at,meta:"成绩更新"});});
  notes.forEach(x=>events.push({id:`note-${x.id}`,type:"note",title:x.title,description:x.content,date:x.occurred_at,meta:LEARNING_RECORD_TYPE_LABELS[x.record_type],noteType:x.record_type,nextAction:x.next_action})); events.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
  const completed=progress.filter(x=>x.status==="completed").length, submitted=submissions.length, practice=conversations.reduce((sum,x)=>sum+x.practice_count,0);
  return <div className="pb-12"><div className="mx-auto mt-5 w-full max-w-[1500px] space-y-5 px-4 sm:px-6 lg:px-8">{canManage&&<div className="flex justify-end"><Link href="/dashboard/admin/records" className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black text-white" style={{backgroundColor:"var(--app-secondary)"}}>进入记录后台<ArrowRight size={15}/></Link></div>}<section className="app-card rounded-3xl border p-5 sm:p-6" style={{background:"linear-gradient(125deg,var(--app-hero-end),var(--app-card-bg),var(--app-accent-soft))"}}><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_500px] xl:items-end"><div><span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-black" style={{color:"var(--app-accent)",backgroundColor:"var(--app-accent-soft)"}}>{canManage?<Eye size={14}/>:<History size={14}/>} {canManage?"学生端只读预览":"我的成长档案"}</span><h1 className="mt-3 text-2xl font-black tracking-tight">每一次学习，都留下清晰记录</h1><p className="app-muted-text mt-2 text-sm leading-6">系统自动记录真实学习行为，后台补充的阶段评价与下一步建议也会出现在同一条时间线上。</p></div><div className="grid grid-cols-3 gap-3">{[["完成课时",completed,CheckCircle2,"var(--app-success)","var(--app-success-soft)"],["任务提交",submitted,Send,"var(--app-secondary)","var(--app-secondary-soft)"],["会话练习",practice,MessageCircleMore,"var(--app-accent)","var(--app-accent-soft)"]].map(([label,value,Icon,color,soft])=>{const I=Icon as typeof History;return <div key={String(label)} className="app-card rounded-2xl border p-4 text-center"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-xl" style={{color:String(color),backgroundColor:String(soft)}}><I size={17}/></span><p className="mt-2 text-2xl font-black">{String(value)}</p><p className="app-muted-text text-xs font-black">{String(label)}</p></div>})}</div></div></section>
  {(progressResult.error||submissionResult.error||conversationResult.error||gradeResult.error||noteResult.error)&&<section className="rounded-2xl border p-4 text-sm font-bold" style={{color:"var(--app-warm)",backgroundColor:"var(--app-warm-soft)"}}>部分学习记录暂时无法读取，请稍后刷新。</section>}
  <section className="app-card rounded-3xl border p-4 sm:p-5"><h2 className="flex items-center gap-2 text-xl font-black"><Sparkles size={19} style={{color:"var(--app-warm)"}}/>学习时间线</h2><div className="mt-6 space-y-4">{events.map(event=>{const style=eventStyle[event.type],Icon=style.icon;return <article key={event.id} className="flex gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl" style={{color:style.color,backgroundColor:style.soft}}><Icon size={18}/></span><div className="app-flat-row min-w-0 flex-1 rounded-2xl p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-black" style={{color:style.color}}>{event.type==="note"&&event.noteType?LEARNING_RECORD_TYPE_LABELS[event.noteType]:style.label}</span>{event.meta&&<span className="app-muted-text text-xs">{event.meta}</span>}<time className="app-muted-text ml-auto text-[10px]">{learningRecordDateFormatter.format(new Date(event.date))}</time></div><h3 className="mt-2 text-sm font-black">{event.title}</h3><p className="app-muted-text mt-2 whitespace-pre-wrap text-xs leading-5">{event.description}</p>{event.nextAction&&<p className="mt-3 rounded-xl px-3 py-2 text-xs leading-5" style={{backgroundColor:"var(--app-success-soft)"}}>下一步：{event.nextAction}</p>}</div></article>})}{events.length===0&&<div className="app-empty-state rounded-2xl p-8 text-center"><History className="mx-auto opacity-30" size={32}/><p className="mt-4 font-black">还没有学习记录</p><p className="app-muted-text mt-2 text-xs">开始课程、提交作业或完成会话练习后会自动生成。</p></div>}</div></section></div></div>;
}
