import sys,importlib.util,json,datetime,hashlib
from pathlib import Path
sys.dont_write_bytecode=True;s=importlib.util.spec_from_file_location('c','/tmp/uply-r7cb-readonly.py');c=importlib.util.module_from_spec(s);s.loader.exec_module(c);D=Path('/tmp/uply-r7cb-b2-contract');start=json.loads((D/'audit-start.json').read_text());base=json.loads((c.a.f.E/'content-freeze-baseline.json').read_text())
assert c.m.schema()==start['schema'];assert c.m.fingerprints()==start['business'];assert c.a.f.d.nodes()==json.loads((c.a.f.E/'final-nodes.json').read_text())['nodes'];assert c.a.f.d.versionFingerprint()['rowSha256']==base['scriptVersionRowSha256'];assert c.a.f.d.digest(c.a.f.objectives())==base['objectiveMapSha256']
mods=c.m.S['digital_textbook_modules'];q="SELECT json_build_object('nodes',(SELECT count(*) FROM public.digital_textbook_nodes WHERE module_id IN (MODS)),'activities',(SELECT count(*) FROM public.digital_textbook_activities WHERE node_id IN (SELECT id FROM public.digital_textbook_nodes WHERE module_id IN (MODS))),'secrets',(SELECT count(*) FROM public.digital_textbook_activity_secrets WHERE activity_id IN (SELECT id FROM public.digital_textbook_activities WHERE node_id IN (SELECT id FROM public.digital_textbook_nodes WHERE module_id IN (MODS)))),'nodeHash',(SELECT encode(sha256(convert_to(id::text,'UTF8')),'hex') FROM public.digital_textbook_nodes WHERE module_id IN (MODS)),'activityHash',(SELECT encode(sha256(convert_to(id::text,'UTF8')),'hex') FROM public.digital_textbook_activities WHERE node_id IN (SELECT id FROM public.digital_textbook_nodes WHERE module_id IN (MODS))))".replace('MODS',mods)
binding=c.m.query(q);prior=json.loads((c.E/'b1d-binding-after.json').read_text());assert [binding[k] for k in ['nodes','activities','secrets']]==[1,1,1];assert binding['nodeHash']==prior['nodeHash'] and binding['activityHash']==prior['activityHash']
tables=['auth.users','auth.identities','auth.sessions','auth.audit_log_entries','public.profiles','public.account_management_audit_logs','public.tenants','public.tenant_memberships','public.digital_textbook_attempts','public.digital_textbook_node_progress','public.digital_textbook_activity_page_progress','public.agent_definition_versions','public.agent_conversations','public.agent_runs','public.agent_messages','public.agent_run_events']
meta=c.m.query("SELECT json_agg(json_build_object('table',table_schema||'.'||table_name,'col',column_name)) FROM information_schema.columns WHERE table_schema||'.'||table_name IN ("+','.join("'"+t+"'" for t in tables)+") AND column_name IN ('created_at','updated_at')")
entries=[]
for t in tables:
 cols=[r['col'] for r in meta if r['table']==t]
 if cols:entries.extend(["'"+t+"'","(SELECT count(*) FROM "+t+' WHERE '+' OR '.join('"'+col+'" >= '+"'"+start['startedAt']+"'::timestamptz" for col in cols)+')'])
changes=c.m.query('SELECT json_build_object('+','.join(entries)+')');assert all(v==0 for v in changes.values())
ops=c.m.inv.operations();assert (Path(ops['pm2']['pm_cwd'])/'.next/BUILD_ID').read_text().strip()=='f3AMbrTZfbg0_VWwnSE6i';assert ops['pm2']['status']=='online'
ledger=c.m.query("SELECT json_build_object('ledger',(SELECT count(*) FROM supabase_migrations.schema_migrations),'latest',(SELECT max(version) FROM supabase_migrations.schema_migrations))");assert ledger['ledger']==458
c.save('b2-production-end-state',{'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'B1':'COMPLETE','binding':binding,'freeze':'UNCHANGED','scriptVersion':'1 DRAFT','nodes':8,'objectives':4,'schema':'UNCHANGED','currentDbCreatedOrUpdatedSinceAudit':changes,'currentDbIdentityWrites':0,'attemptWrites':0,'progressWrites':0,'agentRuns':0,'providerRequests':0,'publish':0,'pins':0,'feature':'OFF','allowlists':'EMPTY','build':'f3AMbrTZfbg0_VWwnSE6i',**ledger,'productionMutations':0,'B2Provisioned':False,'R7D':'NOT READY','Stage1G':'NOT READY','evidenceLimit':'Read-only hashes plus aggregate creation/update timestamps and execution trace; no WAL audit.'})
print('{"currentDbWrites":0,"frozen":"UNCHANGED","binding":[1,1,1],"ledger":458}')
