import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const runtime = await import(process.env.LMS_PGLITE_MODULE ?? '@electric-sql/pglite').catch(() => null);
test('practice binding migration enforces approval, isolation, stale-write checks and frozen student content', { skip: !runtime && 'Set LMS_PGLITE_MODULE to a local PGlite module to run the isolated PostgreSQL test.' }, async () => {
  const db = new runtime.PGlite();
  const app = '10000000-0000-0000-0000-000000000001';
  const otherApp = '10000000-0000-0000-0000-000000000002';
  const chapter = '20000000-0000-0000-0000-000000000001';
  const node = '30000000-0000-0000-0000-000000000001';
  const grammarNode = '30000000-0000-0000-0000-000000000000';
  const grammar = { title: '입니다', meaning: '是', examples: [{ ko: '학생입니다.', zh: '是学生。', audio: 'audio.mp3' }] };
  const value = { ko: '학교', zh: '学校', pos: '', collocation: '', transcription: '' };
  const snapshot = [{ nodeId: grammarNode, kind: 'grammar', value: grammar }, { nodeId: node, kind: 'vocabulary', value }];
  try {
    await db.exec(`
      create role anon; create role authenticated;
      alter default privileges in schema public grant execute on functions to anon, authenticated;
      create schema auth; create schema private;
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid', true), '')::uuid $$;
      create function public.current_user_can_manage_standard_question_bank() returns boolean language sql stable as $$ select current_setting('test.manager', true) = 'true' $$;
      create function private.current_user_can_read_student_app(id uuid) returns boolean language sql stable as $$ select id::text = current_setting('test.app', true) $$;
      create table public.student_apps(id uuid primary key);
      create table public.digital_textbooks(id uuid primary key, student_app_id uuid, lesson_id uuid, status text);
      create table public.digital_textbook_versions(id uuid primary key, textbook_id uuid, status text);
      create table public.digital_textbook_chapters(id uuid primary key, version_id uuid, chapter_test_id uuid, status text);
      create table public.digital_textbook_modules(id uuid primary key, chapter_id uuid, module_code text);
      create table public.digital_textbook_nodes(id uuid primary key, module_id uuid, content jsonb);
      insert into public.student_apps values ('${app}'), ('${otherApp}');
      insert into public.digital_textbooks values ('${app}', '${app}', '${app}', 'published');
      insert into public.digital_textbook_versions values ('${app}', '${app}', 'published');
      insert into public.digital_textbook_chapters values ('${chapter}', '${app}', '${chapter}', 'published');
      insert into public.digital_textbook_modules values ('${node}', '${chapter}', 'vocabulary'), ('${grammarNode}', '${chapter}', 'grammar');
      select set_config('test.uid', '${app}', false), set_config('test.manager', 'true', false), set_config('test.app', '${app}', false);
    `);
    await db.query('insert into public.digital_textbook_nodes values ($1, $1, $2)', [node, { vocabulary: [value] }]);
    await db.query('insert into public.digital_textbook_nodes values ($1, $1, $2)', [grammarNode, { grammar: [grammar] }]);
    await db.exec(await readFile(new URL('../supabase/migrations/202609080001_chapter_practice_bindings.sql', import.meta.url), 'utf8'));
    await db.exec(await readFile(new URL('../supabase/migrations/202609080002_chapter_practice_explicit_function_grants.sql', import.meta.url), 'utf8'));
    const review = (revision, items, enabled = true, appId = app) => db.query('select public.review_chapter_practice_binding($1, $2, $3, $4, $5)', [appId, chapter, revision, JSON.stringify(items), enabled]);
    const read = (appId = app) => db.query('select * from public.read_chapter_practice_snapshots($1)', [appId]);
    await db.exec('set role authenticated');
    await review(0, snapshot);
    assert.deepEqual((await read()).rows[0].snapshot, snapshot);
    await assert.rejects(review(0, snapshot), /关联已被修改/);
    await assert.rejects(review(1, snapshot, true, otherApp), /当前应用/);
    assert.equal((await read(otherApp)).rows.length, 0);
    await assert.rejects(db.exec("update public.chapter_practice_bindings set is_enabled = false"), /permission denied/);
    await db.exec('reset role');
    const changed = [snapshot[0], { ...snapshot[1], value: { ...value, zh: '学校（更新）' } }];
    await db.query('update public.digital_textbook_nodes set content = $1 where id = $2', [{ vocabulary: [changed[1].value] }, node]);
    await db.exec('set role authenticated');
    assert.deepEqual((await read()).rows[0].snapshot, snapshot, 'source edits must never silently replace approved content');
    await assert.rejects(review(1, snapshot), /内容已变化/);
    await review(1, changed);
    await assert.rejects(review(1, changed), /关联已被修改/);
    assert.deepEqual((await read()).rows[0].snapshot, changed);
    await review(2, [], false);
    assert.equal((await read()).rows.length, 0);
    await review(3, changed);
    await db.exec('reset role');
    await db.exec("update public.digital_textbook_versions set status = 'archived'");
    await db.exec('set role authenticated');
    assert.equal((await read()).rows.length, 0);
    await assert.rejects(review(4, changed), /已发布/);
    await db.exec("select set_config('test.manager', 'false', false)");
    assert.equal((await db.query('select * from public.chapter_practice_bindings')).rows.length, 0);
    await assert.rejects(review(4, [], false), /没有权限/);
    await db.exec("select set_config('test.uid', '', false), set_config('test.manager', 'true', false)");
    await assert.rejects(review(4, [], false), /没有权限/);
    assert.equal((await read()).rows.length, 0);
    await db.exec('reset role; set role anon');
    await assert.rejects(read(), /permission denied/);
  } finally { await db.close(); }
});
