import './fixtures/smart-textbook-legacy-adapter/register-server-only.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { transportFixture, req } from './fixtures/teaching-agent/student-transport.mjs';
import { koreanHarness, requestFixture, providerFixture, responseStream, toolResponse, withStudentRuntimeDatabase } from './fixtures/teaching-agent/student-runtime.mjs';
import { ids } from './fixtures/teaching-agent/student-domain.mjs';
const {projectStudentSelectionPins}=await import('../src/features/teaching-agent/server/page-projection/selection-projection.ts');
const {createStudentAiTeacherClient,studentRunBusy,studentErrorMessage}=await import('../src/features/teaching-agent/client/student-ai-teacher-client.ts');
const {explainRequest}=await import('../src/features/teaching-agent/client/selection-state.ts');
const {createStudentTransportHandlers}=await import('../src/features/teaching-agent/server/transport/student-handlers.ts');
const {ActiveRunAbortRegistry}=await import('../src/features/teaching-agent/server/transport/active-run-abort-registry.ts');
const {createStudentRunStore}=await import('../src/features/teaching-agent/server/transport/run-store.ts');
const {createStudentAiTeacherRuntime}=await import('../src/features/teaching-agent/server/runtime/create-student-ai-teacher-runtime.ts');
const {SupabaseAgentRepositories}=await import('../src/features/agent-core/persistence/supabase/repositories.ts');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async fn=>{for(let i=0;i<250;i++){if(await fn())return;await delay(10);}assert.fail('timeout');};
async function pinsFor(h){const i=await requestFixture(h,{session:false});return projectStudentSelectionPins({candidates:[i.selection],authenticate:h.authenticate,repository:h.repository,execution:{signal:new AbortController().signal,runId:randomUUID(),deadlineAt:new Date(Date.now()+40000).toISOString()}});}
function wire(handlers,intercept){const calls=[];return {calls,fetch:async(path,init={})=>{calls.push({path,init});if(intercept){const v=await intercept(path,init,calls);if(v)return v;}const request=new Request('http://localhost'+path,{...init,headers:{origin:'http://localhost',...init.headers}});const m=path.match(/\/runs\/([^/]+)(\/cancel)?$/);return m?(m[2]?handlers.cancel(request,m[1]):handlers.status(request,m[1])):handlers.post(request);}};}
function manual(events,status){const id=randomUUID(),conversationId=randomUUID();let calls=[];return {id,calls,fetch:async(path,init)=>{calls.push({path,init});if(init?.method!=='POST')return Response.json({protocolVersion:1,runId:id,conversationId,status:'completed',finalAnswer:'恢复的解释',sourceRefs:['ta1:segment:'+'a'.repeat(64)],completeness:'complete',createdAt:new Date().toISOString(),endedAt:new Date().toISOString(),...status});let seq=0;return new Response(new ReadableStream({start(c){for(const e of events)c.enqueue(new TextEncoder().encode(JSON.stringify({protocolVersion:1,runId:id,conversationId,seq:++seq,at:new Date().toISOString(),...e})+'\n'));c.close();}}),{headers:{'content-type':'application/x-ndjson'}});}};}
test('server pins reuse authorized published segmentation; client text edits do not affect request pins',async()=>{const h=koreanHarness(),pins=await pinsFor(h);assert.equal(pins.length,4);const a=pins.find(p=>p.locale==='zh-CN'&&p.segmentIndex===0);assert.equal(a.displayText,'저는 학생입니다.');
 const i=await requestFixture(h,{session:false});assert.equal(a.segmentRef,i.selection.segmentRef);assert.equal(a.expectedRevision,i.selection.expectedRevision);
 assert.deepEqual(explainRequest({...a,displayText:'FAKE DOM TEXT'},'same-key'),explainRequest(a,'same-key'));assert.doesNotMatch(JSON.stringify(pins),/actorId|tenantId|authority|sourceLocale|sourceRefs|correctAnswer/);
 h.setIdentity({actorId:ids.B1,tenantId:ids.B});assert.deepEqual(await projectStudentSelectionPins({candidates:[i.selection],authenticate:h.authenticate,repository:h.repository,execution:{signal:new AbortController().signal,runId:randomUUID(),deadlineAt:new Date(Date.now()+40000).toISOString()}}),[]);
});
test('selection A then B uses corresponding server pins and clears prior answer',async()=>{const f=await transportFixture(),pins=(await pinsFor(f.h)).filter(p=>p.locale==='zh-CN'),w=wire(f.handlers),c=createStudentAiTeacherClient({fetch:w.fetch,retryDelays:[0]});
 await c.start(pins[0]);assert.equal(c.getSnapshot().phase,'completed');const p=c.start(pins[1]);assert.equal(c.getSnapshot().answer,undefined);assert.equal(c.getSnapshot().selection.segmentRef,pins[1].segmentRef);await p;
 const posts=w.calls.filter(c=>c.path.endsWith('/runs')).map(c=>JSON.parse(c.init.body));assert.equal(posts[0].selection.segmentRef,pins[0].segmentRef);assert.equal(posts[1].selection.segmentRef,pins[1].segmentRef);assert.notEqual(posts[0].idempotencyKey,posts[1].idempotencyKey);c.dispose();});
test('double click and B while A active create one logical request; terminal retry uses new key',async()=>{let release;const pause=new Promise(r=>release=r);const f=await transportFixture({provider:providerFixture([async b=>{await pause;return responseStream(toolResponse(b));}])});const pins=await pinsFor(f.h),w=wire(f.handlers),c=createStudentAiTeacherClient({fetch:w.fetch,retryDelays:[0]});const p=c.start(pins[0]);await c.start(pins[1]);assert.equal(w.calls.filter(x=>x.path.endsWith('/runs')).length,1);release();await p;assert.equal(c.getSnapshot().phase,'completed');c.dispose();});
test('unknown admission retry reuses key; completed transport replay adds no Provider calls',async()=>{const f=await transportFixture(),pin=(await pinsFor(f.h))[0];let fail=true;const w=wire(f.handlers),c=createStudentAiTeacherClient({retryDelays:[0],fetch:async(path,init)=>{if(fail){fail=false;const r=await w.fetch(path,init);await r.text();throw new TypeError('network');}return w.fetch(path,init);}});
 await c.start(pin);assert.equal(c.getSnapshot().uncertain,true);const count=f.provider.calls.length;await c.retry();assert.equal(c.getSnapshot().phase,'completed');assert.equal(f.provider.calls.length,count);assert.equal(JSON.parse(w.calls[0].init.body).idempotencyKey,JSON.parse(w.calls[1].init.body).idempotencyKey);c.dispose();});
test('stream ends after started: GET restores completed without another POST',async()=>{const f=await transportFixture(),pin=(await pinsFor(f.h))[0],m=manual([{type:'run.started'}]),c=createStudentAiTeacherClient({fetch:m.fetch,retryDelays:[0]});await c.start(pin);assert.equal(c.getSnapshot().phase,'completed');assert.equal(c.getSnapshot().answer.text,'恢复的解释');assert.equal(m.calls.filter(x=>x.init?.method==='POST').length,1);c.dispose();});
test('GET polling bounded; running remains uncertain, never auto POST',async()=>{const f=await transportFixture(),pin=(await pinsFor(f.h))[0],m=manual([{type:'run.started'}],{status:'running',finalAnswer:undefined,sourceRefs:undefined,completeness:undefined}),c=createStudentAiTeacherClient({fetch:m.fetch,retryDelays:[0,0,0]});await c.start(pin);assert.equal(c.getSnapshot().phase,'recovering');assert.equal(m.calls.length,4);assert.ok(studentRunBusy(c.getSnapshot()));c.dispose();});
test('answer.final alone is not completed; subsequent failure clears provisional answer',async()=>{const f=await transportFixture(),pin=(await pinsFor(f.h))[0],m=manual([{type:'run.started'},{type:'answer.final',text:'临时解释',sourceRefs:['ta1:segment:'+'a'.repeat(64)],completeness:'complete'},{type:'run.failed',code:'SKILL_OUTPUT_INVALID',safeMessage:'PRIVATE',partial:false}]);const c=createStudentAiTeacherClient({fetch:m.fetch}),states=[];c.subscribe(()=>states.push(c.getSnapshot()));await c.start(pin);assert.equal(c.getSnapshot().phase,'failed');assert.equal(c.getSnapshot().answer,undefined);assert.ok(states.some(s=>s.answer&&s.phase!=='completed'));c.dispose();});
test('completed with missing source evidence fails protocol and never labels grounded',async()=>{const f=await transportFixture(),pin=(await pinsFor(f.h))[0],m=manual([{type:'run.started'},{type:'answer.final',text:'bad',sourceRefs:[],completeness:'complete'},{type:'run.completed',usageStatus:'unknown'}],{sourceRefs:[]});const c=createStudentAiTeacherClient({fetch:m.fetch,retryDelays:[0]});await c.start(pin);assert.notEqual(c.getSnapshot().phase,'completed');assert.equal(c.getSnapshot().answer,undefined);c.dispose();});
test('persistent cancel endpoint is called and only terminal status declares cancelled',async()=>{let release;const pause=new Promise(r=>release=r),f=await transportFixture({provider:providerFixture([async b=>{await pause;return responseStream(toolResponse(b));}])}),pin=(await pinsFor(f.h))[0],w=wire(f.handlers),c=createStudentAiTeacherClient({fetch:w.fetch,retryDelays:[0,10,20]});const p=c.start(pin);await wait(()=>c.getSnapshot().runId);const stop=c.cancel();assert.equal(c.getSnapshot().phase,'cancelling');release();await stop;await p;assert.equal(c.getSnapshot().phase,'cancelled');assert.ok(w.calls.some(x=>x.path.endsWith('/cancel')));c.dispose();});
test('route dispose cancels, drops late answers, has no classroom endpoints or storage',async()=>{let release;const pause=new Promise(r=>release=r),f=await transportFixture({provider:providerFixture([async b=>{await pause;return responseStream(toolResponse(b));}])}),pin=(await pinsFor(f.h))[0],w=wire(f.handlers),c=createStudentAiTeacherClient({fetch:w.fetch});const p=c.start(pin);await wait(()=>c.getSnapshot().runId);c.dispose();release();await p;assert.equal(c.getSnapshot().answer,undefined);assert.ok(w.calls.some(x=>x.path.endsWith('/cancel')));assert.ok(w.calls.every(x=>x.path.startsWith('/api/teaching-agent/runs')));});
test('stale version rejected by real Runtime; clear selection, safe message; no fallback',async()=>{const f=await transportFixture(),pin=(await pinsFor(f.h))[0];f.h.rows.learning_agent_script_nodes[0].updated_at=new Date().toISOString();const w=wire(f.handlers),c=createStudentAiTeacherClient({fetch:w.fetch});await c.start(pin);assert.equal(c.getSnapshot().selection,null);assert.equal(c.getSnapshot().invalidSelection,true);assert.match(studentErrorMessage(c.getSnapshot().error),/重新选择/);assert.equal(f.provider.calls.length,0);c.dispose();});
for(const code of ['FEATURE_DISABLED','UNAUTHENTICATED','FORBIDDEN','RUN_NOT_FOUND','CONVERSATION_BUSY','IDEMPOTENCY_CONFLICT','DEADLINE_EXCEEDED','REQUIRED_EVIDENCE_MISSING','SKILL_OUTPUT_INVALID','PROVIDER_UNAVAILABLE'])test(`safe UI error mapping ${code}`,()=>assert.doesNotMatch(studentErrorMessage(code),/DeepSeek|Tool|Skill|Supabase|SQL|tenant|enrollment|UNAUTHENTICATED/));
test('static: public client import graph excludes private modules; existing classroom only receives a slot',()=>{for(const root of ['src/features/teaching-agent/client','src/features/teaching-agent/components'])for(const file of readdirSync(root)){if(!/\.tsx?$/.test(file))continue;const s=readFileSync(root+'/'+file,'utf8');assert.doesNotMatch(s,/from ['"][^'"]*(?:\/server\/|\/providers\/|\/persistence\/|\/skills\/|\/tools\/|contracts\/server)/);assert.doesNotMatch(s,/localStorage|sessionStorage|console\.log|learning-agent\/respond|tutorReply|crypto\.subtle|createHash|process\.env/);}
 const shell=readFileSync('src/app/dashboard/courses/[categorySlug]/[subcategorySlug]/[courseSlug]/[lessonSlug]/KoreanLevelOneSmartTextbook.tsx','utf8');assert.match(shell,/teachingAgentSlots\?\.\[activeModule.id\]\?\.\[locale\]/);assert.doesNotMatch(shell,/from ['"][^'"]*teaching-agent|fetch\(['"]\/api\/teaching-agent/);
 const source=readFileSync('src/features/teaching-agent/server/page-projection/selection-projection.ts','utf8');assert.match(source,/selectionPins\(content/);assert.doesNotMatch(source,/createHash|\.rpc\(|\.update\(|\.insert\(/);
});
test('isolated SQL: server pins -> UI controller -> real Transport/Runtime -> cancel/close; 23 teaching tables unchanged',{skip:process.env.RUN_TEACHING_AGENT_ISOLATED_DB_TESTS!=='1',timeout:180000},async t=>{
 await withStudentRuntimeDatabase(async f=>{const before=f.hashes(),owner=await f.h.authenticate(),store=createStudentRunStore(f.client,owner);let provider=providerFixture();const handlers=createStudentTransportHandlers({enabled:()=>true,registry:new ActiveRunAbortRegistry(),authenticate:async()=>({owner,store,allowAdmission:async()=>true,runtime:createStudentAiTeacherRuntime({authenticate:f.h.authenticate,repository:f.h.repository,provider:provider.provider,persistence:a=>new SupabaseAgentRepositories(f.client,a),checkCancellation:store.checkCancellation})})});
 const pins=await pinsFor(f.h),w=wire(handlers),c=createStudentAiTeacherClient({fetch:w.fetch,retryDelays:[0,20,40]});await c.start(pins[0]);assert.equal(c.getSnapshot().phase,'completed');assert.deepEqual(f.hashes(),before);c.dispose();assert.deepEqual(f.hashes(),before);
 let release;const pause=new Promise(r=>release=r);provider=providerFixture([async b=>{await pause;return responseStream(toolResponse(b));}]);const d=createStudentAiTeacherClient({fetch:w.fetch,retryDelays:[0,20,40]});const pending=d.start(pins[0]);await wait(()=>d.getSnapshot().runId);const stop=d.cancel();release();await stop;await pending;assert.equal(d.getSnapshot().phase,'cancelled');d.dispose();assert.deepEqual(f.hashes(),before);writeFileSync('/tmp/uply-stage1e-db-results.json',JSON.stringify({before,after:f.hashes(),teachingTables:Object.keys(before).length,liveProviderRequests:0},null,2));t.diagnostic('UI controller / real Runtime: 23 teaching table hashes unchanged; live requests 0');
 },{transport:true});
});

test('late GET running snapshot cannot overwrite a newer stream completed event',async()=>{
 const f=await transportFixture(),pin=(await pinsFor(f.h))[0],id=randomUUID(),conversationId=randomUUID();let output,resolveGet;
 const get=new Promise(r=>resolveGet=r);let seq=0;const send=e=>output.enqueue(new TextEncoder().encode(JSON.stringify({protocolVersion:1,runId:id,conversationId,seq:++seq,at:new Date().toISOString(),...e})+'\n'));
 const c=createStudentAiTeacherClient({retryDelays:[0],fetch:async(path,init)=>init?.method==='POST'?new Response(new ReadableStream({start(ctrl){output=ctrl;send({type:'run.started'});}}),{headers:{'content-type':'application/x-ndjson'}}):get});
 const pending=c.start(pin);await wait(()=>c.getSnapshot().runId);const recovery=c.recover();send({type:'answer.final',text:'已完成的讲解',sourceRefs:[pin.segmentRef],completeness:'complete'});send({type:'run.completed',usageStatus:'unknown'});output.close();await pending;assert.equal(c.getSnapshot().phase,'completed');
 resolveGet(Response.json({protocolVersion:1,runId:id,conversationId,status:'running',createdAt:new Date().toISOString(),endedAt:null}));await recovery;assert.equal(c.getSnapshot().phase,'completed');c.dispose();
});
