import assert from 'node:assert/strict';
import test from 'node:test';
import {createFixture,manifest} from './fixtures/teaching-agent-r7b/fixture.server.mjs';
import {executionBinding,acceptCompletion} from '../src/features/smart-textbook-runtime/core/execution-contracts.ts';
const make=(f,id='request-test')=>({binding:executionBinding(manifest,f.context,manifest.execution.cues[0]),requestId:id,generation:1});
test('R7B server private grader and request idempotency; completed does not mean lesson complete',()=>{const f=createFixture(),r=make(f);f.checkpoint(r);const a=f.submit(r,'option-1'),b=f.submit(r,'option-1');assert.deepEqual(a,b);assert.equal(f.metrics.submits,1);assert.equal(a.receipt.status,'COMPLETED');assert.equal(a.result.nodeCompleted,false);assert.throws(()=>f.submit(r,'option-0'));});
test('R7B activity evidence distinguishes content revision and state revision',()=>{const f=createFixture(),r=make(f);const before=f.checkpoint(r),after=f.submit(r,'option-1').receipt;assert.equal(after.binding.snapshotDigest,before.binding.snapshotDigest);assert.ok(after.evidence.stateRevision>before.evidence.stateRevision);assert.equal(after.generation,1);assert.equal(acceptCompletion(after,r).status,'COMPLETED');assert.throws(()=>acceptCompletion(before,r,after.evidence.stateRevision));});
for(const field of ['sessionId','snapshotId','snapshotDigest','stepId','sourceBlockId','mediaRevision','cueId','blockId','activityRef'])test(`R7B mismatched completion ${field} rejected`,()=>{const f=createFixture(),r=make(f);f.checkpoint(r);const receipt=f.submit(r,'option-1').receipt;receipt.binding={...receipt.binding,[field]:'invalid'};assert.throws(()=>acceptCompletion(receipt,r));});
test('R7B stale request/generation and fabricated completed status rejected',()=>{const f=createFixture(),r=make(f),before=f.checkpoint(r);assert.throws(()=>acceptCompletion({...before,status:'COMPLETED'},r));assert.throws(()=>acceptCompletion({...before,generation:0},r));assert.throws(()=>acceptCompletion({...before,requestId:'wrong'},r));});
