import assert from 'node:assert/strict';
import test from 'node:test';
import {createFixture,manifest} from './fixtures/teaching-agent-r7b/fixture.server.mjs';
import {StepController} from '../src/features/smart-textbook-runtime/core/step-controller.ts';
import {NativeMediaController} from '../src/features/smart-textbook-runtime/core/native-media-controller.ts';
import {createRuntimeFactsReadPort} from '../src/features/smart-textbook-runtime/core/runtime-facts.ts';
function wait(owner,predicate){if(predicate(owner.snapshot()))return Promise.resolve();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{off();reject(Error('state condition timeout'));},2000);const off=owner.subscribe(()=>{if(predicate(owner.snapshot())){off();clearTimeout(timer);resolve();}});});}
async function setup(fixture=createFixture(),overrides={}){const steps=new StepController(manifest),ports={...fixture.ports(),...overrides},owner=new NativeMediaController(manifest,fixture.context,steps,ports);const media={paused:true,currentTime:0,duration:30,plays:0,pauses:0,async play(){this.plays++;this.paused=false;},pause(){this.pauses++;this.paused=true;}};owner.attach(media,'test-video');await wait(owner,s=>s.restored||s.phase==='ERROR');return {fixture,steps,owner,media};}
async function trigger(x,time=6){await x.owner.play();x.media.currentTime=time;x.owner.observe(time);await wait(x.owner,s=>s.phase==='AWAITING_ACTIVITY');}
test('R7B happy path, authoritative evidence, dedupe, backward seek, no Step completion',async()=>{const x=await setup();try{const read=createRuntimeFactsReadPort(x.owner).read;assert.equal(read().runtimePhase,'READY');await trigger(x);assert.equal(x.media.paused,true);assert.equal(read().runtimePhase,'AWAITING_ACTIVITY');
 for(let i=0;i<10;i++)x.owner.observe(6+i/100);assert.equal(x.fixture.metrics.checkpoints,1);
 await x.owner.submit('test-activity','option-1');await wait(x.owner,s=>s.phase==='PLAYING');assert.equal(x.media.plays,2);assert.equal(read().completion.status,'COMPLETED');assert.equal(read().stateEvidence.source,'isolated-fixture');
 x.owner.seek(2);x.owner.observe(8);assert.equal(x.fixture.metrics.checkpoints,1);assert.deepEqual(x.fixture.initialState.completedStepIds,[]);assert.doesNotMatch(JSON.stringify(read()),/answerKey|correctAnswer|correctIndex|正确答案|privateAnswer/);
}finally{x.steps.dispose();}});
test('R7B wrong answer holds and deliberate next submission completes',async()=>{const x=await setup();try{await trigger(x);await x.owner.submit('test-activity','option-0');assert.equal(x.owner.snapshot().phase,'AWAITING_ACTIVITY');assert.equal(x.media.paused,true);assert.equal(x.media.plays,1);await x.owner.submit('test-activity','option-1');await wait(x.owner,s=>s.phase==='PLAYING');}finally{x.steps.dispose();}});
test('R7B lost completion response readback; no resubmit',async()=>{const x=await setup();try{await trigger(x);x.fixture.setMode('lost-completed');await x.owner.submit('test-activity','option-1');await wait(x.owner,s=>s.phase==='PLAYING');assert.equal(x.fixture.metrics.submits,1);assert.equal(x.fixture.metrics.readbacks,1);}finally{x.steps.dispose();}});
test('R7B UNKNOWN readback holds without automatic retry',async()=>{const x=await setup();try{await trigger(x);x.fixture.setMode('unknown');await x.owner.submit('test-activity','option-1');assert.equal(x.owner.snapshot().unknown,true);assert.equal(x.media.paused,true);await x.owner.submit('test-activity','option-1');assert.equal(x.fixture.metrics.submits,1);assert.equal(x.fixture.metrics.readbacks,1);}finally{x.steps.dispose();}});
test('R7B mandatory forward seek and seek landing dedupe',async()=>{const x=await setup();try{await x.owner.play();x.owner.observe(2);x.owner.seek(20);await wait(x.owner,s=>s.phase==='AWAITING_ACTIVITY');x.owner.observe(20,true);x.owner.observe(20.1);assert.equal(x.fixture.metrics.checkpoints,1);assert.equal(x.media.paused,true);}finally{x.steps.dispose();}});
test('R7B refresh waiting and completed restore use server state, not position',async()=>{const f=createFixture(),x=await setup(f);await trigger(x);x.steps.dispose();const y=await setup(f);assert.equal(y.owner.snapshot().phase,'AWAITING_ACTIVITY');assert.equal(y.media.plays,0);await y.owner.submit('test-activity','option-1');assert.equal(y.owner.snapshot().phase,'RESUME_READY');y.steps.dispose();const z=await setup(f);try{assert.equal(z.owner.snapshot().phase,'RESUME_READY');await z.owner.play();z.owner.observe(10);assert.equal(z.owner.snapshot().visibleActivity,null);assert.equal(f.metrics.checkpoints,1);}finally{z.steps.dispose();}});
test('R7B invalid restore fails closed',async()=>{const f=createFixture();f.setMode('invalid-restore');const x=await setup(f);try{assert.equal(x.owner.snapshot().phase,'ERROR');await x.owner.play();assert.equal(x.media.plays,0);}finally{x.steps.dispose();}});
test('R7B late generation result cannot resume new media',async()=>{let release,entered;const called=new Promise(r=>entered=r),f=createFixture(),x=await setup(f,{submit:async(r,o)=>{const result=f.submit(r,o);entered();await new Promise(r=>release=r);return result;}});await trigger(x);const pending=x.owner.submit('test-activity','option-1');await called;x.steps.dispose();const y=await setup(f);release();await pending;assert.equal(y.media.plays,0);assert.equal(y.owner.snapshot().phase,'RESUME_READY');y.steps.dispose();});
test('R7B user pause intent survives activity completion',async()=>{const x=await setup();try{await trigger(x);x.owner.userPause();await x.owner.submit('test-activity','option-1');assert.equal(x.owner.snapshot().phase,'RESUME_READY');assert.equal(x.media.plays,1);assert.equal(x.media.paused,true);}finally{x.steps.dispose();}});
test('R7B autoplay reject once remains resume-ready',async()=>{const x=await setup();try{x.media.play=async()=>{x.media.plays++;throw Error('NotAllowedError');};await x.owner.play();assert.equal(x.owner.snapshot().event,'AUTOPLAY_BLOCKED');assert.equal(x.media.plays,1);assert.equal(x.owner.snapshot().phase,'RESUME_READY');}finally{x.steps.dispose();}});
test('R7B media error and ended never complete lesson',async()=>{const x=await setup();try{x.owner.mediaError();x.owner.observe(10);await x.owner.play();assert.equal(x.fixture.metrics.checkpoints,0);assert.equal(x.media.plays,0);assert.equal(x.owner.snapshot().phase,'ERROR');x.owner.ended();assert.equal(x.owner.snapshot().phase,'ERROR');}finally{x.steps.dispose();}});
test('R7B duplicate submission callback cannot cause a second attempt or resume',async()=>{let release,entered;const called=new Promise(r=>entered=r),f=createFixture(),x=await setup(f,{submit:async(r,o)=>{const value=f.submit(r,o);entered();await new Promise(r=>release=r);return value;}});try{await trigger(x);const first=x.owner.submit('test-activity','option-1');await called;assert.equal(await x.owner.submit('test-activity','option-1'),null);release();await first;await wait(x.owner,s=>s.phase==='PLAYING');await x.owner.readback();assert.equal(f.metrics.submits,1);assert.equal(x.media.plays,2);}finally{x.steps.dispose();}});
test('R7B facts read port is read-only and video position remains observation',async()=>{const x=await setup();try{const port=createRuntimeFactsReadPort(x.owner),metrics=JSON.stringify(x.fixture.metrics);const a=port.read(),b=port.read();assert.deepEqual(a,b);assert.equal(JSON.stringify(x.fixture.metrics),metrics);assert.deepEqual(Object.keys(port),['read']);assert.equal(a.clientObservation.authoritativeProgress,false);assert.equal(a.source,'lesson-runtime');assert.equal(a.snapshot.digest,manifest.snapshot.contentDigest);assert.equal(a.generation,x.steps.generation);}finally{x.steps.dispose();}});
test('R7B malformed or stale readback cannot authorize resume',async()=>{const f=createFixture(),x=await setup(f,{submit:async()=>{throw Error('lost');},readback:async r=>({...f.readback(r),generation:r.generation+1})});try{await trigger(x);await x.owner.submit('test-activity','option-1');assert.equal(x.owner.snapshot().unknown,true);assert.equal(x.media.plays,1);assert.equal(x.media.paused,true);}finally{x.steps.dispose();}});
test('R7B actual media duration validation rejects cue outside media',async()=>{const x=await setup();try{x.owner.metadata(4);assert.equal(x.owner.snapshot().phase,'ERROR');await x.owner.play();assert.equal(x.media.plays,0);}finally{x.steps.dispose();}});
test('R7B late play promise after cue pause cannot reset state to PLAYING',async()=>{const x=await setup();let release;try{x.media.play=()=>{x.media.plays++;x.media.paused=false;return new Promise(r=>release=r);};const play=x.owner.play();x.owner.observe(8);await wait(x.owner,s=>s.phase==='AWAITING_ACTIVITY');release();await play;assert.equal(x.owner.snapshot().phase,'AWAITING_ACTIVITY');assert.equal(x.media.paused,true);}finally{x.steps.dispose();}});
test('R7B submission timeout holds until authoritative readback, without retry',async()=>{const f=createFixture(),x=await setup(f,{submit:async(r,o)=>{f.submit(r,o);return new Promise(()=>{});}});try{await trigger(x);const pending=x.owner.submit('test-activity','option-1');assert.equal(x.owner.snapshot().phase,'CHECKING_COMPLETION');assert.equal(x.media.paused,true);await pending;await wait(x.owner,s=>s.phase==='PLAYING');assert.equal(f.metrics.submits,1);assert.equal(f.metrics.readbacks,1);}finally{x.steps.dispose();}});
test('R7B target registry has exactly one scoped media play owner',async()=>{const {RuntimeTargetRegistry}=await import('../src/features/smart-textbook-runtime/core/target-registry.ts');const x=await setup(),registry=new RuntimeTargetRegistry(manifest.runtimeTargets,x.steps),id=manifest.blocks.find(b=>b.type==='video').runtimeTarget;try{registry.mount(id,{dispose(){},reveal(){}});const off=registry.mountNativeMediaOwner(id,()=>x.owner.play());assert.equal(registry.commandOwnerCount(id,'play'),1);assert.throws(()=>registry.mountNativeMediaOwner(id,()=>x.owner.play()));await registry.command(id,'play');assert.equal(x.media.plays,1);off();assert.equal(registry.commandOwnerCount(id,'play'),0);}finally{x.steps.dispose();}});
test('R7B a later DOM play implementation cannot compete with the native owner',async()=>{const {RuntimeTargetRegistry}=await import('../src/features/smart-textbook-runtime/core/target-registry.ts');const x=await setup(),registry=new RuntimeTargetRegistry(manifest.runtimeTargets,x.steps),id=manifest.blocks.find(b=>b.type==='video').runtimeTarget;try{registry.mountNativeMediaOwner(id,()=>x.owner.play());assert.throws(()=>registry.mount(id,{dispose(){},play(){}}));assert.equal(registry.commandOwnerCount(id,'play'),1);}finally{x.steps.dispose();}});
test('R7B UNKNOWN restore holds even when pending checkpoint is unavailable',async()=>{const f=createFixture(),x=await setup(f,{restore:async r=>({...f.restore(r),pending:false,receipt:{...f.restore(r).receipt,status:'UNKNOWN'}})});try{assert.equal(x.owner.snapshot().phase,'AWAITING_ACTIVITY');assert.equal(x.owner.snapshot().unknown,true);await x.owner.play();assert.equal(x.media.plays,0);}finally{x.steps.dispose();}});

test('R7C regression: valid submit COMPLETED cannot override independent INCOMPLETE readback',async()=>{
 const f=createFixture(),x=await setup(f,{readback:async r=>({...f.readback(r),status:'INCOMPLETE',completedAt:null})});
 try{await trigger(x);await x.owner.submit('test-activity','option-1');assert.equal(x.media.paused,true);assert.equal(x.media.plays,1);assert.equal(x.owner.snapshot().phase,'AWAITING_ACTIVITY');assert.equal(f.metrics.readbacks,1);}finally{x.steps.dispose();}
});
