import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {mkdtemp,chmod,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const hooks=registerHooks({resolve(s,c,n){if(s==='server-only')return{url:'data:text/javascript,export{}',shortCircuit:true};return n(s,c);}});
const {provisionDevelopmentExecution:run}=await import('../src/features/development-execution/server/provisioning.service.ts');
const {DEVELOPMENT_BINDING:B}=await import('../src/features/development-execution/server/provisioning-contract.ts');
const {createProvisioningJournal}=await import('../src/features/development-execution/server/provisioning-journal.server.ts');
hooks.deregister();
function harness(){
 const now=Date.now(),e={enabled:true,environment:B.environment,databaseIdentity:B.databaseIdentity,expiresAt:new Date(now+600000).toISOString()};
 const s={databaseIdentity:B.databaseIdentity,observedAt:new Date(now).toISOString(),canonicalValid:true,tenants:[],actors:[]};
 const tenant={id:'10000000-0000-4000-8000-000000000001',alias:B.tenantAlias,plan:'starter'};
 const actor={id:'10000000-0000-4000-8000-000000000002',email:B.email,purpose:B.actorAlias,human:false,productionAllowed:false,banUntil:new Date(now+172800000).toISOString(),sessions:0,refreshTokens:0,identityCount:1,emailIdentityCount:1,provisionedProductionAccount:false,profile:{role:'student',globalRole:'member',status:'active'},memberships:[]};
 const calls=[],dispatches=[];let claim=false,reads=0,password;
 const h={environment:e,now:()=>now,s,calls,dispatches,actor,tenant,reader:{async read(){reads++;return structuredClone(s);}},journal:{async claim(){if(claim)return false;claim=true;return true;},async dispatched(stage){dispatches.push(stage);},async finish(){}},writer:{async createTenant(){calls.push('TENANT');s.tenants.push(structuredClone(tenant));},async createInitiallyBannedActor(p){password=p;calls.push('ACTOR');s.actors.push(structuredClone(actor));},async deactivateProfile(){calls.push('PROFILE');s.actors[0].profile.status='inactive';},async createSuspendedMembership(){calls.push('MEMBERSHIP');s.actors[0].memberships.push({tenantId:tenant.id,role:'student',status:'suspended',isDefault:false});}},get reads(){return reads;},get password(){return password;}};return h;
}
test('fixed four-operation workflow; independent readback; no ID/password DTO; no attempt scope',async()=>{const h=harness();const r=await run(h);assert.equal(r.status,'CREATED');assert.equal(r.scope,'DISABLED');assert.deepEqual(h.calls,['TENANT','ACTOR','PROFILE','MEMBERSHIP']);assert.deepEqual(h.calls,h.dispatches);assert.equal(h.reads,6);assert.equal(h.password.length,48);assert.doesNotMatch(JSON.stringify(r),/synthetic|10000000|password|token/);assert.equal((await run(h)).status,'EXISTING');assert.equal(h.calls.length,4);});
for(const [name,change] of Object.entries({disabled:h=>h.environment.enabled=false,environment:h=>h.environment.environment='production',database:h=>h.environment.databaseIdentity='wrong',expiry:h=>h.environment.expiresAt=new Date(0).toISOString(),readDB:h=>h.s.databaseIdentity='wrong',stale:h=>h.s.observedAt=new Date(0).toISOString(),freeze:h=>h.s.canonicalValid=false}))test(`${name} denies before writes`,async()=>{const h=harness();change(h);assert.equal((await run(h)).status,'DENIED');assert.equal(h.calls.length,0);});
for(const kind of ['tenant','actor','duplicate'])test(`${kind} existing partial state never repaired automatically`,async()=>{const h=harness();if(kind==='actor')h.s.actors.push(h.actor);else h.s.tenants.push(h.tenant);if(kind==='duplicate')h.s.tenants.push(h.tenant);assert.equal((await run(h)).status,'VERIFY_REQUIRED');assert.equal(h.calls.length,0);});
for(const [name,change] of Object.entries({unbanned:a=>a.banUntil=null,shortBan:a=>a.banUntil=new Date(Date.now()+3600000).toISOString(),session:a=>a.sessions=1,refresh:a=>a.refreshTokens=1,owner:a=>a.profile.globalRole='platform_owner',admin:a=>a.profile.role='tenant_super_admin',production:a=>a.provisionedProductionAccount=true,identity:a=>a.identityCount=2}))test(`unsafe actor ${name}: stop before profile/membership`,async()=>{const h=harness();change(h.actor);assert.equal((await run(h)).status,'VERIFY_REQUIRED');assert.deepEqual(h.calls,['TENANT','ACTOR']);});
for(const stage of ['createTenant','createInitiallyBannedActor','deactivateProfile','createSuspendedMembership'])for(const committed of [false,true])test(`UNKNOWN ${stage}, committed=${committed}: readback only, no retry`,async()=>{const h=harness(),original=h.writer[stage];let n=0;h.writer[stage]=async(...a)=>{n++;if(committed)await original(...a);throw Error('lost response');};const r=await run(h);assert.equal(r.status,'VERIFY_REQUIRED');assert.equal(n,1);const calls=h.calls.length;await run(h);assert.equal(n,1);assert.equal(h.calls.length,calls);if(stage==='createSuspendedMembership'&&committed)assert.equal(r.classification,'COMPLETE');});
test('readback failure stays UNKNOWN; never retries mutation',async()=>{const h=harness(),read=h.reader.read;h.reader.read=async()=>{if(h.calls.length)throw Error('transport');return read();};const r=await run(h);assert.equal(r.classification,'UNKNOWN');assert.deepEqual(h.calls,['TENANT']);});
test('expiry after tenant blocks actor',async()=>{const h=harness();h.now=()=>Date.now()+(h.calls.length?7200000:0);assert.equal((await run(h)).status,'VERIFY_REQUIRED');assert.deepEqual(h.calls,['TENANT']);});
test('suspended non-default membership required',async()=>{const h=harness(),f=h.writer.createSuspendedMembership;h.writer.createSuspendedMembership=async()=>{await f();h.s.actors[0].memberships[0].isDefault=true;};assert.equal((await run(h)).classification,'INVALID');});
test('durable journal concurrency and restart fence; no credentials in journal',async()=>{const dir=await mkdtemp(join(tmpdir(),'b2-journal-'));await chmod(dir,0o700);try{const a=createProvisioningJournal(dir),b=createProvisioningJournal(dir);const claims=await Promise.all([a.claim(),b.claim()]);assert.equal(claims.filter(Boolean).length,1);const winner=claims[0]?a:b;await winner.dispatched('ACTOR');await winner.finish({status:'VERIFY_REQUIRED'});assert.equal(await createProvisioningJournal(dir).claim(),false);const data=await readFile(join(dir,'development-domain-execution-v1.provision.jsonl'),'utf8');assert.doesNotMatch(data,/password|token|synthetic|actorId/);}finally{await rm(dir,{recursive:true});}});
