import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import {mkdtemp,chmod,rm} from 'node:fs/promises';
let snapshot='';globalThis.b3Sql=()=>`BEGIN READ ONLY;WITH l AS(SELECT 1) SELECT '${snapshot.replaceAll("'","''")}'::jsonb; COMMIT;`;
registerHooks({resolve(s,c,n){if(s==='@/lib/admin')return {url:'data:text/javascript,export const requirePlatformOwner=async()=>{}',shortCircuit:true};if(s==='@/lib/supabase/admin')return {url:'data:text/javascript,export const createAdminClient=()=>{throw Error("ISOLATED_ONLY")}',shortCircuit:true};if(s==='./provisioning-readback.server.ts'&&c.parentURL?.endsWith('execution-guard.server.ts'))return {url:'data:text/javascript,export const createProvisioningReadback=t=>({read:()=>t.transaction(globalThis.b3Sql())})',shortCircuit:true};return n(s,c);}});
await import('./fixtures/teaching-agent-r7b/fixture.server.mjs');
const {composeExecution}=await import('../src/features/development-execution/server/execution-composition.server.ts');
const {createExecutionJournal}=await import('../src/features/development-execution/server/execution-journal.server.ts');
const {B3_BUDGET}=await import('../src/features/development-execution/server/execution-scope.server.ts');
const {DEVELOPMENT_BINDING:B}=await import('../src/features/development-execution/server/provisioning-contract.ts');
const {startDatabase,seedFixture,literal:q,startService}=await import('./fixtures/teaching-agent-r7c/postgres.mjs');
const {createDurableFixture}=await import('./fixtures/teaching-agent-r7c/fixture.server.mjs');
const {StepController}=await import('../src/features/smart-textbook-runtime/core/step-controller.ts');
const {NativeMediaController}=await import('../src/features/smart-textbook-runtime/core/native-media-controller.ts');
const {createRuntimeFactsReadPort}=await import('../src/features/smart-textbook-runtime/core/runtime-facts.ts');
const ready=(o,p=s=>s.restored)=>p(o.snapshot())?Promise.resolve():new Promise((resolve,reject)=>{const timer=setTimeout(()=>{off();console.log('STATE_WAIT',JSON.stringify(o.snapshot()));reject(Error('STATE_TIMEOUT'));},5000);const off=o.subscribe(()=>{if(p(o.snapshot())){off();clearTimeout(timer);resolve();}});});
test('real B3 composition / Runtime wrong hold / suppressed committed correct / independent readback resumes',async t=>{
 const db=await startDatabase(),dir=await mkdtemp('/tmp/b3a-composition-');await chmod(dir,0o700);let steps,child;
 try{
  const ids=await seedFixture({...db,raw:s=>db.raw(s.replace(',20,true)',',3,true)'))});
  await db.raw(`CREATE TABLE public.profiles(id uuid);CREATE TABLE public.tenant_memberships(user_id uuid,tenant_id uuid);CREATE TABLE public.digital_textbook_activity_page_progress(tenant_id uuid,student_id uuid,activity_id uuid);INSERT INTO public.profiles VALUES(${q(ids.actorId)});INSERT INTO public.tenant_memberships VALUES(${q(ids.actorId)},${q(ids.tenantId)});`);
  const f=await createDurableFixture(db,ids),state={databaseIdentity:B.databaseIdentity,observedAt:new Date().toISOString(),canonicalValid:true,tenants:[{id:ids.tenantId,alias:B.tenantAlias,plan:'starter'}],actors:[{id:ids.actorId,email:B.email,purpose:B.actorAlias,human:false,productionAllowed:false,banUntil:new Date(Date.now()+100000000).toISOString(),sessions:0,refreshTokens:0,identityCount:1,emailIdentityCount:1,provisionedProductionAccount:false,profile:{role:'student',globalRole:'member',status:'inactive'},memberships:[{tenantId:ids.tenantId,role:'student',status:'suspended',isDefault:false}]}]};
  snapshot=JSON.stringify(state);
  const p={transport:db,reader:{read:async()=>({...state,observedAt:new Date().toISOString()})},domain:f.scope,definitionDigest:f.definition.digest,manifest:f.manifest,context:f.context,binding:f.binding};
  const s={contract:'development-domain-execution/1',scenarioId:'r7cb-b3-wrong-correct-recovery-1',environment:B.environment,databaseIdentity:B.databaseIdentity,issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+600000).toISOString(),binding:f.binding,domain:f.scope,generation:0,state:'ACTIVE',budget:B3_BUDGET},j=createExecutionJournal(dir);await j.activate(s);
  const service=await composeExecution(p,s,j),ports={...service,restore:r=>service.restore(r,false),mediaSource:()=>'/media'},media={paused:true,currentTime:0,duration:30,plays:0,pause(){this.paused=true;},async play(){this.paused=false;this.plays++;}};
  steps=new StepController(f.manifest);const runtime=new NativeMediaController(f.manifest,f.context,steps,ports);runtime.attach(media,'test-video');await ready(runtime);const correct=f.definition.secret.answer_key.value,wrong=(correct+1)%3;
  await runtime.play();runtime.seek(12);await ready(runtime,x=>x.phase==='AWAITING_ACTIVITY');
  await t.test('wrong durable incomplete holds existing media owner',async()=>{await runtime.submit('test-activity',`option-${wrong}`);assert.equal(media.paused,true);assert.equal(runtime.snapshot().phase,'AWAITING_ACTIVITY');assert.equal((await f.repository.read(f.scope)).attempts.length,1);});
  await t.test('second commit response suppressed, readback only resumes and closes scope',async()=>{await runtime.submit('test-activity',`option-${correct}`);assert.equal(runtime.snapshot().phase,'PLAYING');assert.equal(media.paused,false);assert.equal((await f.repository.read(f.scope)).attempts.length,2);assert.equal(await j.enabled(),false);});
  await t.test('third submission denied; facts carry no answer/identity secrets',async()=>{await assert.rejects(service.submit({binding:f.binding,requestId:'third',generation:1},`option-${correct}`));assert.equal((await f.repository.read(f.scope)).attempts.length,2);assert.doesNotMatch(JSON.stringify(createRuntimeFactsReadPort(runtime).read()),/answer_key|optionIndex|definitionDigest|service_role|password/);});
  await t.test('reconstructed read-only composition restores completed and cannot submit',async()=>{const restored=await composeExecution(p,s,createExecutionJournal(dir),true);const r={binding:f.binding,requestId:'recovery',generation:2};assert.equal((await restored.readback(r)).status,'COMPLETED');await assert.rejects(restored.submit(r,`option-${correct}`));});
  await t.test('owned server child actually exits/restarts; only readback, durable counts unchanged',async()=>{child=await startService(db,ids);const old=child.pid;await child.stop();child=await startService(db,ids);assert.notEqual(child.pid,old);const response=await fetch(child.url+'/readback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({request:{binding:f.binding,requestId:'restart-read',generation:2}})});assert.equal((await response.json()).status,'COMPLETED');assert.equal((await f.repository.read(f.scope)).attempts.length,2);});
 }finally{steps?.dispose();await child?.stop();await db.stop();await rm(dir,{recursive:true,force:true});}
});
