import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const runtime = await import(process.env.LMS_PGLITE_MODULE ?? '@electric-sql/pglite').catch(() => null);

test('source review tracks material, activities and scripts and gates publication without impersonation', { skip: !runtime && 'Set LMS_PGLITE_MODULE to run isolated PostgreSQL tests.' }, async () => {
  const db = new runtime.PGlite();
  const id = '10000000-0000-0000-0000-000000000001';
  const other = '10000000-0000-0000-0000-000000000002';
  try {
    await db.exec(`
      create role anon; create role authenticated;
      alter default privileges in schema public grant execute on functions to anon, authenticated;
      create schema private; create schema auth;
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
      create function private.is_platform_owner() returns boolean language sql stable as $$ select current_setting('test.owner',true) = 'true' $$;
      create table public.digital_textbooks(id uuid primary key, student_app_id uuid);
      create table public.digital_textbook_versions(id uuid primary key, textbook_id uuid);
      create table public.digital_textbook_chapters(id uuid primary key, version_id uuid);
      create table public.digital_textbook_modules(id uuid primary key, chapter_id uuid, title jsonb);
      create table public.digital_textbook_nodes(id uuid primary key, module_id uuid, content jsonb);
      create table public.digital_textbook_activities(id uuid primary key, node_id uuid, prompt jsonb);
      create table public.digital_textbook_activity_secrets(activity_id uuid primary key, answer_key jsonb);
      create table public.learning_agent_lessons(id uuid primary key, module_id uuid);
      create table public.learning_agent_script_versions(id uuid primary key, lesson_id uuid, title jsonb, status text);
      create table public.learning_agent_script_nodes(id uuid primary key, script_version_id uuid, teacher_script jsonb);
      create table public.learning_agent_node_interaction_secrets(node_id uuid primary key, correct_option_index integer);
      insert into public.digital_textbooks values('${id}','${id}');
      insert into public.digital_textbook_versions values('${id}','${id}');
      insert into public.digital_textbook_chapters values('${id}','${id}');
      insert into public.digital_textbook_modules values('${id}','${id}','{"zh-CN":"词汇"}');
      insert into public.digital_textbook_nodes values('${id}','${id}','{"vocabulary":[{"ko":"학교","zh":"学校"}]}');
      insert into public.digital_textbook_activities values('${id}','${id}','{"zh-CN":"请选择"}');
      insert into public.digital_textbook_activity_secrets values('${id}','{"correctOptionIndex":0}');
      insert into public.learning_agent_lessons values('${id}','${id}');
      insert into public.learning_agent_script_versions values('${id}','${id}','{"zh-CN":"词汇教学"}','draft');
      insert into public.learning_agent_script_nodes values('${id}','${id}','{"zh-CN":"学校"}');
      insert into public.learning_agent_node_interaction_secrets values('${id}',0);
      select set_config('test.uid','${id}',false), set_config('test.owner','true',false);
    `);
    await db.exec(await readFile(new URL('../supabase/migrations/202609080003_teaching_script_source_reviews.sql', import.meta.url), 'utf8'));
    const get = async () => (await db.query('select public.get_teaching_script_source_review($1) as review', [id])).rows[0].review;
    const confirm = review => db.query('select public.confirm_teaching_script_source_review($1,$2,$3,$4)', [id, review.revision, JSON.stringify(review.source), review.scriptToken]);
    await assert.rejects(db.exec("update public.learning_agent_script_versions set status = 'published'"), /尚未复核/);
    let review = await get();
    assert.equal(review.status, 'unreviewed');
    await db.exec('set role authenticated');
    await confirm(review);
    assert.equal((await get()).status, 'reviewed');
    await assert.rejects(confirm(review), /复核记录已被更新/);
    await assert.rejects(db.exec('select * from public.teaching_script_source_reviews'), /permission denied/);
    await db.exec('reset role');
    await db.exec("update public.digital_textbook_activities set prompt = '{\"zh-CN\":\"新的问题\"}'");
    assert.equal((await get()).sourceChanged, true);
    await assert.rejects(db.exec("update public.learning_agent_script_versions set status = 'published'"), /尚未复核/);
    review = await get();
    await db.exec("update public.learning_agent_script_nodes set teacher_script = '{\"zh-CN\":\"新的讲解\"}'");
    await assert.rejects(confirm(review), /核对期间/);
    assert.equal((await get()).scriptChanged, true);
    await confirm(await get());
    await db.exec("update public.learning_agent_script_versions set status = 'published'");
    assert.equal((await get()).status, 'reviewed');
    await db.exec(`insert into public.digital_textbook_nodes values('${other}','${id}','{"grammar":[]}')`);
    assert.equal((await get()).status, 'changed', 'new textbook nodes invalidate review');
    assert.equal((await db.query('select status from public.learning_agent_script_versions')).rows[0].status, 'published', 'source edits do not unpublish existing lessons');
    await confirm(await get());
    await db.exec("update public.digital_textbook_activity_secrets set answer_key = '{\"correctOptionIndex\":1}'");
    assert.equal((await get()).sourceChanged, true, 'textbook answer changes invalidate review');
    await confirm(await get());
    await db.exec('update public.learning_agent_node_interaction_secrets set correct_option_index = 1');
    assert.equal((await get()).scriptChanged, true);
    const statuses = (await db.query('select * from public.list_teaching_script_source_review_status($1)', [id])).rows;
    assert.deepEqual(statuses, [{ script_version_id: id, review_status: 'changed' }]);
    assert.equal((await db.query('select * from public.list_teaching_script_source_review_status($1)', [other])).rows.length, 0);
    await db.exec("select set_config('test.owner','false',false); set role authenticated");
    await assert.rejects(get(), /只有平台负责人/);
    await assert.rejects(confirm(review), /只有平台负责人/);
    await db.exec('reset role; set role anon');
    await assert.rejects(get(), /permission denied/);
    await assert.rejects(confirm(review), /permission denied/);
  } finally { await db.close(); }
});
