import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {readFileSync} from 'node:fs';
const hooks=registerHooks({resolve(s,c,n){if(s==='server-only')return{url:'data:text/javascript,export{}',shortCircuit:true};if(s==='@/lib/admin')return{url:'data:text/javascript,export const requirePlatformOwner=()=>{throw Error("UNUSED")}',shortCircuit:true};if(s==='@/lib/supabase/admin')return{url:'data:text/javascript,export const createAdminClient=()=>{throw Error("UNEXPECTED_ADMIN")}',shortCircuit:true};return n(s,c);}});
const entry=await import('../src/features/development-execution/server/provisioning-entrypoint.server.ts');
const {DEVELOPMENT_BINDING:B}=await import('../src/features/development-execution/server/provisioning-contract.ts');hooks.deregister();
const now=Date.now();
// Public origin only, no credentials: derive from canonical operations fixture,
// whose identity hash is independently locked. Never contact this URL in tests.
const apiOrigin=JSON.parse(readFileSync('/home/yangzhen/.config/uply-first-enable-20260910/runtime.json','utf8')).NEXT_PUBLIC_SUPABASE_URL;
const facts={now,cwd:entry.CANONICAL_DIRECTORY,buildId:'testBuildIdentifier123',apiOrigin,runtimeHash:'7a4b31b099fb968dd1105f8fbc67b946ae3fa79c30873998f8864ef1578878c8'};
const approval={contract:'development-provisioning-entrypoint/1',approval:'Approval B',enabled:true,environment:B.environment,databaseIdentity:B.databaseIdentity,apiOriginSha256:B.apiOriginSha256,budgetSha256:entry.BUDGET_SHA256,dbServiceSha256:'9540a50b93e528433a856aba8f2f98029c488cb8f3dd68f6a30941629a8fdb8c',runtimeSha256:facts.runtimeHash,buildId:facts.buildId,issuedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+600000).toISOString()};
test('fixed approved development installation admitted',()=>assert.equal(entry.validateEntrypointApproval(approval,facts).approval,'Approval B'));
for(const [name,change]of Object.entries({environment:a=>a.environment='production',database:a=>a.databaseIdentity='wrong',origin:a=>a.apiOriginSha256='wrong',budget:a=>a.budgetSha256='wrong',disabled:a=>a.enabled=false,expiry:a=>a.expiresAt=new Date(now-1).toISOString(),longWindow:a=>a.issuedAt=new Date(now-1800000).toISOString(),futureIssue:a=>a.issuedAt=new Date(now+1000).toISOString(),actorId:a=>a.actorId='untrusted',tenantId:a=>a.tenantId='untrusted',url:a=>a.dbUrl='https://untrusted.invalid'}))test(`${name} authorization refused`,()=>{const a=structuredClone(approval);change(a);assert.throws(()=>entry.validateEntrypointApproval(a,facts));});
for(const k of ['cwd','buildId','apiOrigin','runtimeHash'])test(`observed ${k} mismatch denied`,()=>assert.throws(()=>entry.validateEntrypointApproval(approval,{...facts,[k]:'mismatch'})));
function fixture(){
 const tenant={id:'10000000-0000-4000-8000-000000000001',alias:B.tenantAlias,plan:'starter'};
 const actor={id:'10000000-0000-4000-8000-000000000002',email:B.email,purpose:B.actorAlias,human:false,productionAllowed:false,banUntil:new Date(now+172800000).toISOString(),sessions:0,refreshTokens:0,identityCount:1,emailIdentityCount:1,provisionedProductionAccount:false,profile:{role:'student',globalRole:'member',status:'active'},memberships:[]};
 const s={databaseIdentity:B.databaseIdentity,observedAt:new Date().toISOString(),canonicalValid:true,tenants:[],actors:[]};const writes=[];let claimed=false,claims=0;
 return{s,actor,tenant,writes,environment:approval,reader:{async read(){return structuredClone({...s,observedAt:new Date().toISOString()});}},claimExists:async()=>claimed,journal:{async claim(){claims++;if(claimed)return false;claimed=true;return true;},async dispatched(){},async finish(){}},writer:{async createTenant(){writes.push('tenant');s.tenants.push(tenant);},async createInitiallyBannedActor(){writes.push('actor');s.actors.push(actor);},async deactivateProfile(){writes.push('profile');actor.profile.status='inactive';},async createSuspendedMembership(){writes.push('membership');actor.memberships.push({tenantId:tenant.id,role:'student',status:'suspended',isDefault:false});}},get claims(){return claims;}};
}
test('read-only page preflight returns safe READY without claiming/writing',async()=>{const h=fixture();assert.deepEqual(await entry.inspectProvisioningEntrypoint(h,h.claimExists),{status:'READY',scope:'DISABLED'});assert.deepEqual(h.writes,[]);assert.equal(h.claims,0);});
test('existing journal disables before service dispatch',async()=>{const h=fixture();const r=await entry.executePreparedProvisioningEntrypoint(h,async()=>true);assert.equal(r.status,'DENIED');assert.equal(h.claims,0);assert.deepEqual(h.writes,[]);});
for(const kind of ['actor','tenant'])test(`partial ${kind} never reaches service`,async()=>{const h=fixture();h.s[kind==='actor'?'actors':'tenants'].push(h[kind]);assert.equal((await entry.executePreparedProvisioningEntrypoint(h,h.claimExists)).status,'DENIED');assert.equal(h.claims,0);});
test('one service transaction sequence; duplicate callback returns safe EXISTING',async()=>{const h=fixture();const first=await entry.executePreparedProvisioningEntrypoint(h,h.claimExists);assert.equal(first.status,'CREATED');const second=await entry.executePreparedProvisioningEntrypoint(h,h.claimExists);assert.equal(second.status,'EXISTING');assert.equal(h.claims,1);assert.deepEqual(h.writes,['tenant','actor','profile','membership']);assert.doesNotMatch(JSON.stringify([first,second]),/10000000|password|token|synthetic|secret|email/);});
test('concurrent duplicate POST produces one claimed service sequence',async()=>{const h=fixture();await Promise.all([entry.executePreparedProvisioningEntrypoint(h,h.claimExists),entry.executePreparedProvisioningEntrypoint(h,h.claimExists)]);assert.deepEqual(h.writes,['tenant','actor','profile','membership']);});
test('UNKNOWN response holds; next request cannot redispatch',async()=>{const h=fixture();h.writer.createTenant=async()=>{h.writes.push('tenant');throw Error('unknown commit');};const r=await entry.executePreparedProvisioningEntrypoint(h,h.claimExists);assert.equal(r.status,'VERIFY_REQUIRED');assert.equal((await entry.executePreparedProvisioningEntrypoint(h,h.claimExists)).status,'DENIED');assert.deepEqual(h.writes,['tenant']);});
for(const kind of ['sessions','refreshTokens','membership','freeze'])test(`${kind} unsafe state blocks`,async()=>{const h=fixture();await entry.executePreparedProvisioningEntrypoint(h,h.claimExists);if(kind==='freeze')h.s.canonicalValid=false;else if(kind==='membership')h.actor.memberships[0].isDefault=true;else h.actor[kind]=1;const n=h.writes.length;try{const r=await entry.executePreparedProvisioningEntrypoint(h,h.claimExists);assert.equal(r.status,'DENIED');}catch(e){assert.match(e.message,/PROVISIONING_READBACK_INVALID/);}assert.equal(h.writes.length,n);});
