import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Award, UsersRound } from "lucide-react";
import { GRADE_ITEM_STATUS_LABELS, type GradeItemStatus, type GradeItemType, type GradeRecordStatus } from "@/app/dashboard/grades/config";
import { requireGradeCenterManager } from "@/lib/grade-center";
import { GradeItemForm, type GradeItemFormValue } from "../GradeItemForm";
import { GradeItemStatusActions } from "../GradeItemStatusActions";
import { GradeRecordForm } from "../GradeRecordForm";

type Item = GradeItemFormValue;
type RecordRow = { student_id: string; record_status: GradeRecordStatus; score: number | null; feedback: string };
type Student = { id: string; full_name: string | null; email: string | null; membership_tier: string | null };
export default async function GradeItemDetailPage({ params }: { params: Promise<{ itemId: string }> }) {
  const { itemId } = await params; const { supabase } = await requireGradeCenterManager(); const [itemResult, recordsResult, studentsResult] = await Promise.all([supabase.from("grade_items").select("id,title,description,item_type,term,total_points,weight_percent,status").eq("id", itemId).maybeSingle(), supabase.from("grade_records").select("student_id,record_status,score,feedback").eq("item_id", itemId), supabase.rpc("list_grade_center_students")]); if (itemResult.error || !itemResult.data) notFound();
  const raw = itemResult.data; const item: Item = { ...raw, item_type: raw.item_type as GradeItemType, status: raw.status as GradeItemStatus }; const records = (recordsResult.data ?? []) as RecordRow[]; const recordByStudent = new Map(records.map((record) => [record.student_id, record])); const students = (studentsResult.data ?? []) as Student[];
  return <div className="mx-auto w-full max-w-[1500px] space-y-5 px-4 py-6 sm:px-6 lg:px-8"><Link href="/dashboard/admin/grades" className="inline-flex items-center gap-2 text-xs font-black app-muted-text"><ArrowLeft size={14} />返回成绩管理</Link><section className="app-card rounded-3xl border p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="flex h-12 w-12 items-center justify-center rounded-2xl" style={{ color: "var(--app-secondary)", backgroundColor: "var(--app-secondary-soft)" }}><Award size={22} /></span><div className="min-w-0 flex-1"><p className="text-xs font-black" style={{ color: "var(--app-secondary)" }}>{GRADE_ITEM_STATUS_LABELS[item.status]}</p><h1 className="mt-1 text-2xl font-black">{item.title}</h1><p className="app-muted-text mt-1 text-xs">满分 {item.total_points} · 已录入 {records.length}/{students.length} 人</p></div><GradeItemStatusActions id={item.id} status={item.status} /></div></section><div className="grid items-start gap-5 xl:grid-cols-[minmax(340px,0.68fr)_minmax(0,1.32fr)]"><section className="app-card rounded-3xl border p-4 sm:p-5"><h2 className="text-lg font-black">项目设置</h2><div className="mt-5"><GradeItemForm item={item} /></div></section><section className="app-card rounded-3xl border p-4 sm:p-5"><h2 className="flex items-center gap-2 text-xl font-black"><UsersRound size={20} style={{ color: "var(--app-accent)" }} />学生成绩录入</h2><p className="app-muted-text mt-1 text-xs">保存后先留在后台，项目发布时学生才能看到。</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{students.map((student) => <article key={student.id} className="app-soft-card rounded-2xl border p-4"><div className="mb-4"><p className="text-sm font-black">{student.full_name?.trim() || "未填写姓名"}</p><p className="app-muted-text mt-1 text-xs">{student.email || "未填写邮箱"}</p></div><GradeRecordForm itemId={item.id} studentId={student.id} totalPoints={Number(item.total_points)} record={recordByStudent.get(student.id)} /></article>)}{students.length === 0 && <p className="app-muted-text col-span-full rounded-2xl border border-dashed p-6 text-center text-xs">暂无正常状态的学生账号。</p>}</div></section></div></div>;
}
