"use client";
import { useActionState } from "react";
import { Save } from "lucide-react";
import { initialLearningRecordActionState } from "@/app/dashboard/records/action-state";
import { createLearningRecordNoteAction, updateLearningRecordNoteAction } from "@/app/dashboard/records/actions";
import { LEARNING_RECORD_TYPE_LABELS, LEARNING_RECORD_VISIBILITY_LABELS, type LearningRecordType, type LearningRecordVisibility } from "@/app/dashboard/records/config";
type Student = { id: string; name: string; email: string };
export type LearningRecordFormValue = { id: string; student_id: string; record_type: LearningRecordType; title: string; content: string; next_action: string; visibility: LearningRecordVisibility; occurred_at: string };
function localDate(value?: string) { const date = value ? new Date(value) : new Date(); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0,16); }
export function LearningRecordForm({ students, note }: { students: Student[]; note?: LearningRecordFormValue }) { const action = note ? updateLearningRecordNoteAction.bind(null, note.id) : createLearningRecordNoteAction; const [state, formAction, pending] = useActionState(action, initialLearningRecordActionState); return <form action={formAction} className="space-y-4"><label className="block text-xs font-black">学生<select name="student_id" required defaultValue={note?.student_id ?? ""} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm"><option value="" disabled>选择学生账号</option>{students.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black">记录类型<select name="record_type" defaultValue={note?.record_type ?? "coaching"} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm">{Object.entries(LEARNING_RECORD_TYPE_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black">可见范围<select name="visibility" defaultValue={note?.visibility ?? "student_visible"} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm">{Object.entries(LEARNING_RECORD_VISIBILITY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label className="block text-xs font-black">记录时间<input type="datetime-local" name="occurred_at" required defaultValue={localDate(note?.occurred_at)} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm" /></label><label className="block text-xs font-black">标题<input name="title" required minLength={2} maxLength={120} defaultValue={note?.title} className="app-input mt-2 w-full rounded-xl border px-4 py-3 text-sm" /></label><label className="block text-xs font-black">记录内容<textarea name="content" required minLength={2} maxLength={5000} rows={6} defaultValue={note?.content} className="app-input mt-2 w-full resize-y rounded-xl border px-4 py-3 text-sm leading-7" /></label><label className="block text-xs font-black">下一步建议<textarea name="next_action" maxLength={2000} rows={3} defaultValue={note?.next_action} className="app-input mt-2 w-full resize-y rounded-xl border px-4 py-3 text-sm leading-7" /></label>{state.message && <p className="rounded-xl px-3 py-2.5 text-xs font-bold" style={{ color: state.status === "error" ? "#c94f45" : "var(--app-success)", backgroundColor: state.status === "error" ? "#fff0ed" : "var(--app-success-soft)" }}>{state.message}</p>}<button type="submit" disabled={pending} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black text-white disabled:opacity-50" style={{ backgroundColor: "var(--app-secondary)" }}><Save size={14} />{pending ? "正在保存…" : note ? "保存修改" : "添加学习记录"}</button></form>; }
