import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Clock3, MessagesSquare } from "lucide-react";

import { getConversationPracticeAccess } from "@/lib/conversation-practice";
import { CONVERSATION_CATEGORY_LABELS, CONVERSATION_DIFFICULTY_LABELS, type ConversationCategory, type ConversationDifficulty } from "../config";


type Scenario = { id: string; title: string; description: string; category: ConversationCategory; difficulty: ConversationDifficulty; duration_minutes: number };

export default async function ConversationCoursePage() {
  const { supabase } = await getConversationPracticeAccess();
  const { data } = await supabase.from("conversation_practice_scenarios").select("id,title,description,category,difficulty,duration_minutes").eq("status", "published").order("sort_order", { ascending: true });
  const scenarios = (data ?? []) as Scenario[];
  return <div className="mx-auto w-full max-w-6xl space-y-5 px-4 py-6 sm:px-6 lg:px-8"><Link href="/dashboard/conversation-practice" className="app-muted-text inline-flex items-center gap-2 text-xs font-black"><ArrowLeft size={14} />返回口语练习</Link><section className="app-card rounded-3xl border p-5 sm:p-6" style={{ background: "linear-gradient(125deg, var(--app-hero-end), var(--app-card-bg), var(--app-success-soft))" }}><span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-black" style={{ color: "var(--app-success)", backgroundColor: "var(--app-success-soft)" }}><BookOpen size={14} />口语练习课程</span><h1 className="mt-3 text-2xl font-black tracking-tight">按情境完成你的口语练习</h1><p className="app-muted-text mt-3 max-w-2xl text-sm leading-6">从日常交流到面试表达，选择一个课程情境开始练习。</p></section><section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{scenarios.map((scenario) => <Link key={scenario.id} href={`/dashboard/conversation-practice/${scenario.id}`} className="app-card group rounded-3xl border p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center gap-2"><span className="rounded-full px-2.5 py-1 text-xs font-black" style={{ color: "var(--app-secondary)", backgroundColor: "var(--app-secondary-soft)" }}>{CONVERSATION_CATEGORY_LABELS[scenario.category]}</span><span className="rounded-full px-2.5 py-1 text-xs font-black" style={{ color: "var(--app-success)", backgroundColor: "var(--app-success-soft)" }}>{CONVERSATION_DIFFICULTY_LABELS[scenario.difficulty]}</span><ArrowRight className="ml-auto transition group-hover:translate-x-1" size={16} /></div><h2 className="mt-4 text-lg font-black">{scenario.title}</h2><p className="app-muted-text mt-2 line-clamp-3 text-xs leading-5">{scenario.description}</p><p className="app-muted-text mt-4 inline-flex items-center gap-1 text-xs font-bold"><Clock3 size={12} />建议 {scenario.duration_minutes} 分钟</p></Link>)}{scenarios.length === 0 && <div className="app-card col-span-full rounded-3xl border border-dashed p-8 text-center"><MessagesSquare className="mx-auto opacity-30" size={32} /><p className="mt-3 font-black">暂时没有开放的口语课程</p></div>}</section></div>;
}
