"use server";

import { revalidatePath } from "next/cache";
import { getGradeCenterAccess, requireGradeCenterManager } from "@/lib/grade-center";
import type { GradeCenterActionState } from "./action-state";
import { GRADE_ITEM_STATUSES, GRADE_ITEM_TYPES, GRADE_RECORD_STATUSES, GRADE_REVIEW_STATUSES, type GradeItemStatus, type GradeItemType, type GradeRecordStatus, type GradeReviewStatus } from "./config";

function result(status: "success" | "error", message: string): GradeCenterActionState { return { status, message }; }
function isUuid(value: string) { return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }
function refreshGrades(itemId?: string) { revalidatePath("/dashboard/grades"); revalidatePath("/dashboard/admin/grades"); revalidatePath("/dashboard/admin"); if (itemId) revalidatePath(`/dashboard/admin/grades/${itemId}`); }

function readItem(formData: FormData) {
  const title = String(formData.get("title") ?? "").trim(); const description = String(formData.get("description") ?? "").trim(); const itemType = String(formData.get("item_type") ?? "other"); const term = String(formData.get("term") ?? "").trim(); const totalPoints = Number(formData.get("total_points")); const weightPercent = Number(formData.get("weight_percent") ?? 0);
  if (title.length < 2 || title.length > 120) return { error: "成绩项目标题需要填写 2 至 120 个字。" } as const;
  if (description.length > 2000 || term.length > 60) return { error: "项目说明或学期名称过长。" } as const;
  if (!(GRADE_ITEM_TYPES as readonly string[]).includes(itemType)) return { error: "请选择有效的成绩类型。" } as const;
  if (!Number.isFinite(totalPoints) || totalPoints <= 0 || totalPoints > 10000) return { error: "满分需要填写 0 至 10000 之间的数值。" } as const;
  if (!Number.isFinite(weightPercent) || weightPercent < 0 || weightPercent > 100) return { error: "成绩权重需要填写 0 至 100。" } as const;
  return { data: { p_title: title, p_description: description, p_item_type: itemType as GradeItemType, p_term: term, p_total_points: totalPoints, p_weight_percent: weightPercent } } as const;
}

export async function createGradeItemAction(_state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; const { supabase } = await requireGradeCenterManager(); const input = readItem(formData); if ("error" in input && input.error) return result("error", input.error); const status: GradeItemStatus = formData.get("intent") === "publish" ? "published" : "draft"; const { data, error } = await supabase.rpc("save_grade_item", { p_id: null, ...input.data, p_status: status }); if (error || !data) return result("error", "成绩项目保存失败。"); refreshGrades(String(data)); return result("success", status === "published" ? "成绩项目已经发布。" : "成绩项目草稿已经保存。"); }
export async function updateGradeItemAction(itemId: string, _state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; if (!isUuid(itemId)) return result("error", "成绩项目编号不正确。"); const { supabase } = await requireGradeCenterManager(); const input = readItem(formData); if ("error" in input && input.error) return result("error", input.error); const status = String(formData.get("status") ?? "draft"); if (!(GRADE_ITEM_STATUSES as readonly string[]).includes(status)) return result("error", "成绩项目状态不正确。"); const { error } = await supabase.rpc("save_grade_item", { p_id: itemId, ...input.data, p_status: status as GradeItemStatus }); if (error) return result("error", "成绩项目修改失败，请检查满分是否低于已有得分。"); refreshGrades(itemId); return result("success", "成绩项目信息已经更新。"); }
export async function changeGradeItemStatusAction(itemId: string, nextStatus: GradeItemStatus, _state: GradeCenterActionState, _formData: FormData): Promise<GradeCenterActionState> { void _state; void _formData; if (!isUuid(itemId) || !(GRADE_ITEM_STATUSES as readonly string[]).includes(nextStatus)) return result("error", "成绩项目编号或状态不正确。"); const { supabase } = await requireGradeCenterManager(); const { error } = await supabase.rpc("change_grade_item_status", { p_item_id: itemId, p_status: nextStatus }); if (error) return result("error", "成绩项目状态更新失败。"); refreshGrades(itemId); return result("success", nextStatus === "published" ? "成绩已经向学生发布。" : nextStatus === "archived" ? "成绩项目已经归档。" : "成绩项目已经转为草稿。"); }
export async function saveGradeRecordAction(itemId: string, studentId: string, _state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; if (!isUuid(itemId) || !isUuid(studentId)) return result("error", "成绩项目或学生编号不正确。"); const { supabase } = await requireGradeCenterManager(); const recordStatus = String(formData.get("record_status") ?? "graded"); const scoreText = String(formData.get("score") ?? ""); const score = scoreText === "" ? null : Number(scoreText); const feedback = String(formData.get("feedback") ?? "").trim(); if (!(GRADE_RECORD_STATUSES as readonly string[]).includes(recordStatus)) return result("error", "成绩记录状态不正确。"); if (recordStatus === "graded" && (score === null || !Number.isFinite(score) || score < 0)) return result("error", "请填写有效得分。"); if (feedback.length > 3000) return result("error", "成绩评语不能超过 3000 个字。"); const { error } = await supabase.rpc("save_grade_record", { p_item_id: itemId, p_student_id: studentId, p_record_status: recordStatus as GradeRecordStatus, p_score: score, p_feedback: feedback }); if (error) return result("error", "成绩保存失败，请确认得分没有超过满分。"); refreshGrades(itemId); return result("success", "该学生的成绩已经保存。"); }
export async function importAssignmentGradesAction(_state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; const assignmentId = String(formData.get("assignment_id") ?? ""); if (!isUuid(assignmentId)) return result("error", "请选择需要同步的作业或考试。"); const { supabase } = await requireGradeCenterManager(); const { data, error } = await supabase.rpc("import_assignment_grades", { p_assignment_id: assignmentId }); if (error || !data) return result("error", "作业考试成绩同步失败。"); refreshGrades(String(data)); return result("success", "已同步最新批改成绩，项目暂存为草稿，请确认后发布。"); }
export async function requestGradeReviewAction(recordId: string, _state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; if (!isUuid(recordId)) return result("error", "成绩记录编号不正确。"); const access = await getGradeCenterAccess(); if (access.role !== "student") return result("error", "当前账号不能申请学生成绩复核。"); const reason = String(formData.get("reason") ?? "").trim(); if (reason.length < 2 || reason.length > 2000) return result("error", "复核原因需要填写 2 至 2000 个字。"); const { error } = await access.supabase.rpc("request_grade_review", { p_record_id: recordId, p_reason: reason }); if (error) return result("error", "复核申请提交失败，可能已有申请正在处理中。"); refreshGrades(); return result("success", "成绩复核申请已经提交。"); }
export async function resolveGradeReviewAction(reviewId: string, _state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; if (!isUuid(reviewId)) return result("error", "复核申请编号不正确。"); const { supabase } = await requireGradeCenterManager(); const status = String(formData.get("status") ?? "reviewing"); const response = String(formData.get("response") ?? "").trim(); if (!(GRADE_REVIEW_STATUSES as readonly string[]).includes(status) || status === "pending") return result("error", "请选择有效的复核处理状态。"); if (response.length > 3000) return result("error", "复核回复不能超过 3000 个字。"); const { error } = await supabase.rpc("resolve_grade_review", { p_review_id: reviewId, p_status: status as GradeReviewStatus, p_response: response }); if (error) return result("error", "复核处理结果保存失败。"); refreshGrades(); return result("success", "复核处理结果已经同步给学生。"); }
export async function grantGradeCenterAdminAction(_state: GradeCenterActionState, formData: FormData): Promise<GradeCenterActionState> { void _state; const access = await getGradeCenterAccess(); if (!access.canAssignAdmins) return result("error", "只有负责人可以指定成绩管理员。"); const adminId = String(formData.get("admin_id") ?? ""); if (!isUuid(adminId)) return result("error", "请选择需要授权的管理员。"); const { data: target } = await access.supabase.from("profiles").select("id,role,status").eq("id", adminId).maybeSingle(); if (!target || target.role !== "admin" || (target.status && target.status !== "active")) return result("error", "只能授权状态正常的管理员账号。"); const { error } = await access.supabase.from("grade_center_admin_assignments").upsert({ admin_id: adminId, granted_by: access.user.id, granted_at: new Date().toISOString(), revoked_by: null, revoked_at: null }, { onConflict: "tenant_id,admin_id" }); if (error) return result("error", "成绩管理员授权失败。"); refreshGrades(); return result("success", "该管理员已经获得成绩后台权限。"); }
export async function revokeGradeCenterAdminAction(adminId: string, _state: GradeCenterActionState, _formData: FormData): Promise<GradeCenterActionState> { void _state; void _formData; const access = await getGradeCenterAccess(); if (!access.canAssignAdmins) return result("error", "只有负责人可以撤销成绩管理员权限。"); if (!isUuid(adminId)) return result("error", "管理员编号不正确。"); const { data, error } = await access.supabase.from("grade_center_admin_assignments").update({ revoked_by: access.user.id, revoked_at: new Date().toISOString() }).eq("admin_id", adminId).is("revoked_at", null).select("admin_id").maybeSingle(); if (error || !data) return result("error", "成绩管理员权限撤销失败。"); refreshGrades(); return result("success", "该管理员的成绩后台权限已经撤销。"); }
