import Link from "next/link";
import { ArrowRight, Award, BookOpenCheck, Eye, SearchCheck, Target, TrendingUp } from "lucide-react";
import { getGradeCenterAccess } from "@/lib/grade-center";
import { GradeReviewForm } from "./GradeReviewForm";
import { GRADE_ITEM_TYPE_LABELS, GRADE_RECORD_STATUS_LABELS, GRADE_REVIEW_STATUS_LABELS, gradeLevel, type GradeItemType, type GradeRecordStatus, type GradeReviewStatus } from "./config";


type Item = { id: string; title: string; description: string; item_type: GradeItemType; term: string; total_points: number; weight_percent: number; source_assignment_id: string | null; published_at: string | null };
type RecordRow = { id: string; item_id: string; record_status: GradeRecordStatus; score: number | null; feedback: string; graded_at: string };
type Review = { id: string; record_id: string; status: GradeReviewStatus; reason: string; response: string; updated_at: string };
type Assignment = { id: string; title: string; description: string; assignment_type: "homework" | "quiz" | "exam"; total_points: number };
type Submission = { assignment_id: string; score: number | null; overall_feedback: string | null; graded_at: string | null; attempt_number: number };

export default async function GradesPage() {
  const { supabase, user, role, canManage } = await getGradeCenterAccess();
  const [itemsResult, recordsResult, reviewsResult, assignmentsResult, submissionsResult] = await Promise.all([
    supabase.from("grade_items").select("id,title,description,item_type,term,total_points,weight_percent,source_assignment_id,published_at").eq("status", "published").order("published_at", { ascending: false }),
    role === "student" ? supabase.from("grade_records").select("id,item_id,record_status,score,feedback,graded_at").eq("student_id", user.id) : Promise.resolve({ data: [] as RecordRow[], error: null }),
    role === "student" ? supabase.from("grade_review_requests").select("id,record_id,status,reason,response,updated_at").eq("student_id", user.id) : Promise.resolve({ data: [] as Review[], error: null }),
    role === "student" ? supabase.from("learning_assignments").select("id,title,description,assignment_type,total_points").eq("status", "published") : Promise.resolve({ data: [] as Assignment[], error: null }),
    role === "student" ? supabase.from("learning_submissions").select("assignment_id,score,overall_feedback,graded_at,attempt_number").eq("student_id", user.id).eq("status", "graded").order("attempt_number", { ascending: false }) : Promise.resolve({ data: [] as Submission[], error: null }),
  ]);
  const items = (itemsResult.data ?? []) as Item[]; const records = (recordsResult.data ?? []) as RecordRow[]; const reviews = (reviewsResult.data ?? []) as Review[];
  const recordByItem = new Map(records.map((item) => [item.item_id, item])); const reviewByRecord = new Map(reviews.map((item) => [item.record_id, item]));
  const importedAssignments = new Set(items.map((item) => item.source_assignment_id).filter(Boolean)); const assignments = (assignmentsResult.data ?? []) as Assignment[]; const assignmentMap = new Map(assignments.map((item) => [item.id, item])); const latestSubmission = new Map<string, Submission>(); for (const item of (submissionsResult.data ?? []) as Submission[]) if (!latestSubmission.has(item.assignment_id)) latestSubmission.set(item.assignment_id, item);
  const manualScores = items.flatMap((item) => { const record = recordByItem.get(item.id); return record?.record_status === "graded" && record.score != null ? [record.score / item.total_points * 100] : []; });
  const assignmentScores = [...latestSubmission.entries()].filter(([id]) => !importedAssignments.has(id)).flatMap(([id, submission]) => { const assignment = assignmentMap.get(id); return assignment && submission.score != null ? [submission.score / assignment.total_points * 100] : []; });
  const allPercent = [...manualScores, ...assignmentScores]; const average = allPercent.length ? allPercent.reduce((a, b) => a + b, 0) / allPercent.length : null; const pendingReviews = reviews.filter((item) => item.status === "pending" || item.status === "reviewing").length;
  return <div className="pb-12"><div className="mx-auto mt-5 w-full max-w-[1500px] space-y-5 px-4 sm:px-6 lg:px-8">{canManage && <div className="flex justify-end"><Link href="/dashboard/admin/grades" className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black text-white" style={{ backgroundColor: "var(--app-secondary)" }}>进入成绩后台<ArrowRight size={15} /></Link></div>}<section className="app-card rounded-3xl border p-5 sm:p-6" style={{ background: "linear-gradient(125deg, var(--app-hero-end), var(--app-card-bg), var(--app-secondary-soft))" }}><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_500px] xl:items-end"><div><span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-black" style={{ color: "var(--app-secondary)", backgroundColor: "var(--app-secondary-soft)" }}>{canManage ? <Eye size={14} /> : <Award size={14} />}{canManage ? "学生端只读预览" : "我的成绩单"}</span><h1 className="mt-3 text-2xl font-black tracking-tight">{average == null ? "成绩发布后会在这里形成成长轨迹" : `${gradeLevel(average)} · 继续稳步向前`}</h1><p className="app-muted-text mt-2 text-sm leading-6">作业考试的已批改成绩自动汇总；后台发布的课程或综合成绩也会显示在同一张成绩单中。</p></div><div className="grid grid-cols-3 gap-3">{[["平均得分率", average == null ? "—" : `${average.toFixed(1)}%`, TrendingUp, "var(--app-accent)", "var(--app-accent-soft)"], ["成绩项目", allPercent.length, Target, "var(--app-secondary)", "var(--app-secondary-soft)"], ["复核处理中", pendingReviews, SearchCheck, "var(--app-warm)", "var(--app-warm-soft)" ]].map(([label, value, Icon, color, soft]) => { const MetricIcon = Icon as typeof Award; return <div key={String(label)} className="app-card rounded-2xl border p-4 text-center"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-xl" style={{ color: String(color), backgroundColor: String(soft) }}><MetricIcon size={17} /></span><p className="mt-2 text-xl font-black">{String(value)}</p><p className="app-muted-text text-xs font-black">{String(label)}</p></div>; })}</div></div></section>
  <section className="grid gap-4 lg:grid-cols-2">{items.map((item) => { const record = recordByItem.get(item.id); const review = record ? reviewByRecord.get(record.id) : undefined; const percent = record?.record_status === "graded" && record.score != null ? record.score / item.total_points * 100 : null; return <article key={item.id} className="app-card rounded-3xl border p-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full px-2.5 py-1 text-xs font-black" style={{ color: "var(--app-secondary)", backgroundColor: "var(--app-secondary-soft)" }}>{GRADE_ITEM_TYPE_LABELS[item.item_type]}</span>{item.term && <span className="app-muted-text text-xs font-bold">{item.term}</span>}{item.weight_percent > 0 && <span className="app-muted-text ml-auto text-xs">权重 {item.weight_percent}%</span>}</div><h2 className="mt-4 text-lg font-black">{item.title}</h2><p className="app-muted-text mt-2 text-xs leading-5">{item.description || "暂无项目说明"}</p>{record ? <div className="mt-4 rounded-2xl p-4" style={{ backgroundColor: "var(--app-soft-bg)" }}><div className="flex items-end justify-between gap-3"><div><p className="text-2xl font-black" style={{ color: percent != null ? "var(--app-success)" : "var(--app-muted)" }}>{record.record_status === "graded" ? record.score ?? 0 : GRADE_RECORD_STATUS_LABELS[record.record_status]}</p>{record.record_status === "graded" && <p className="app-muted-text text-xs">满分 {item.total_points} · {percent?.toFixed(1)}%</p>}</div>{percent != null && <strong style={{ color: "var(--app-success)" }}>{gradeLevel(percent)}</strong>}</div>{record.feedback && <p className="mt-3 border-t pt-3 text-xs leading-5" style={{ borderColor: "var(--app-border-soft)" }}>评语：{record.feedback}</p>}</div> : <p className="app-muted-text mt-4 rounded-xl border border-dashed p-4 text-center text-xs">该项目暂未录入你的成绩。</p>}{review && <div className="mt-3 rounded-xl px-3 py-3 text-xs" style={{ backgroundColor: "var(--app-warm-soft)" }}><p className="font-black">复核状态：{GRADE_REVIEW_STATUS_LABELS[review.status]}</p>{review.response && <p className="mt-2 leading-6">后台回复：{review.response}</p>}</div>}{role === "student" && record && record.record_status === "graded" && (!review || review.status === "resolved" || review.status === "rejected") && <div className="mt-3"><GradeReviewForm recordId={record.id} /></div>}</article>; })}
  {[...latestSubmission.entries()].filter(([id]) => !importedAssignments.has(id)).map(([id, submission]) => { const assignment = assignmentMap.get(id); if (!assignment || submission.score == null) return null; const percent = submission.score / assignment.total_points * 100; return <article key={`assignment-${id}`} className="app-card rounded-3xl border p-5"><div className="flex items-center gap-2"><span className="rounded-full px-2.5 py-1 text-xs font-black" style={{ color: "var(--app-accent)", backgroundColor: "var(--app-accent-soft)" }}>作业考试成绩</span><Link href={`/dashboard/assignments/${id}`} className="ml-auto inline-flex items-center gap-1 text-xs font-black">查看作答<ArrowRight size={11} /></Link></div><h2 className="mt-4 text-lg font-black">{assignment.title}</h2><div className="mt-4 rounded-2xl p-4" style={{ backgroundColor: "var(--app-soft-bg)" }}><p className="text-2xl font-black" style={{ color: "var(--app-success)" }}>{submission.score}</p><p className="app-muted-text text-xs">满分 {assignment.total_points} · {percent.toFixed(1)}% · {gradeLevel(percent)}</p>{submission.overall_feedback && <p className="mt-3 border-t pt-3 text-xs leading-5" style={{ borderColor: "var(--app-border-soft)" }}>评语：{submission.overall_feedback}</p>}</div></article>; })}
  {items.length === 0 && latestSubmission.size === 0 && <div className="app-card col-span-full rounded-3xl border border-dashed p-8 text-center"><BookOpenCheck className="mx-auto opacity-30" size={34} /><p className="mt-4 font-black">当前还没有已发布成绩</p><p className="app-muted-text mt-2 text-sm">老师完成批改或后台发布成绩后会自动显示。</p></div>}</section></div></div>;
}
