import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CirclePlus,
  Columns3,
  Ellipsis,
  Eye,
  KeyRound,
  LoaderCircle,
  Pencil,
  RotateCcw,
  Search,
  ShieldCheck,
  Trash2,
  UserPlus,
  Users,
  X,
} from "lucide-react";

export const Icons = {
  add: CirclePlus,
  addUser: UserPlus,
  alert: CircleAlert,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  columns: Columns3,
  edit: Pencil,
  more: Ellipsis,
  permissions: KeyRound,
  reset: RotateCcw,
  search: Search,
  shield: ShieldCheck,
  sort: ArrowUpDown,
  sortAscending: ArrowUp,
  sortDescending: ArrowDown,
  spinner: LoaderCircle,
  trash: Trash2,
  users: Users,
  view: Eye,
  close: X,
} as const;

export type IconName = keyof typeof Icons;
