"use client";

import { useActionState } from "react";
import { Save } from "lucide-react";

import { initialHelpCenterActionState } from "@/app/dashboard/help/action-state";
import { updateHelpTicketAction } from "@/app/dashboard/help/actions";
import { HELP_TICKET_PRIORITY_LABELS, HELP_TICKET_STATUS_LABELS, type HelpTicketPriority, type HelpTicketStatus } from "@/app/dashboard/help/config";

export function HelpTicketManager({ ticketId, status, priority, resolution }: { ticketId: string; status: HelpTicketStatus; priority: HelpTicketPriority; resolution: string }) { const action = updateHelpTicketAction.bind(null, ticketId); const [state, formAction, pending] = useActionState(action, initialHelpCenterActionState); return <form action={formAction} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black">处理状态<select name="status" defaultValue={status} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm">{Object.entries(HELP_TICKET_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black">紧急程度<select name="priority" defaultValue={priority} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm">{Object.entries(HELP_TICKET_PRIORITY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label className="block text-xs font-black">处理结果<textarea name="resolution" maxLength={3000} rows={5} defaultValue={resolution} placeholder="解决后填写最终处理结果，学生端会同步显示。" className="app-input mt-2 w-full resize-y rounded-xl border px-4 py-3 text-sm leading-6" /></label>{state.message && <p className="text-xs font-bold" style={{ color: state.status === "error" ? "#c94f45" : "var(--app-success)" }}>{state.message}</p>}<button type="submit" disabled={pending} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black text-white disabled:opacity-50" style={{ backgroundColor: "var(--app-secondary)" }}><Save size={14} />{pending ? "正在保存…" : "保存处理状态"}</button></form>; }
