"use client";

import { useActionState } from "react";
import { ShieldCheck, ShieldOff, UserPlus } from "lucide-react";
import { initialHelpCenterActionState } from "@/app/dashboard/help/action-state";
import { grantHelpCenterAdminAction, revokeHelpCenterAdminAction } from "@/app/dashboard/help/actions";

type Admin = { id: string; name: string; email: string; assigned: boolean };
function Revoke({ id }: { id: string }) { const action = revokeHelpCenterAdminAction.bind(null, id); const [state, formAction, pending] = useActionState(action, initialHelpCenterActionState); return <form action={formAction}><button type="submit" disabled={pending} title={state.message || undefined} className="inline-flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-xs font-black disabled:opacity-50" style={{ color: "#c94f45", backgroundColor: "#fff0ed" }}><ShieldOff size={11} />撤销</button></form>; }
export function HelpCenterAdminManager({ admins }: { admins: Admin[] }) { const [state, formAction, pending] = useActionState(grantHelpCenterAdminAction, initialHelpCenterActionState); const available = admins.filter((item) => !item.assigned); const assigned = admins.filter((item) => item.assigned); return <section className="app-card rounded-3xl border p-4 sm:p-5"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl" style={{ color: "var(--app-success)", backgroundColor: "var(--app-success-soft)" }}><ShieldCheck size={19} /></span><div><h2 className="text-lg font-black">帮助中心管理员</h2><p className="app-muted-text mt-1 text-xs leading-5">只有负责人可以授权普通管理员；CEO 自动拥有后台权限。</p></div></div><form action={formAction} className="mt-5 flex flex-col gap-2 sm:flex-row"><select name="admin_id" required defaultValue="" className="app-input min-w-0 flex-1 rounded-xl border px-3 py-3 text-xs"><option value="" disabled>选择普通管理员</option>{available.map((admin) => <option key={admin.id} value={admin.id}>{admin.name} · {admin.email}</option>)}</select><button type="submit" disabled={pending || available.length === 0} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-xs font-black text-white disabled:opacity-50" style={{ backgroundColor: "var(--app-success)" }}><UserPlus size={14} />授权</button></form>{state.message && <p className="mt-3 text-xs font-bold" style={{ color: state.status === "error" ? "#c94f45" : "var(--app-success)" }}>{state.message}</p>}<div className="mt-4 space-y-2">{assigned.map((admin) => <div key={admin.id} className="app-soft-card flex items-center gap-3 rounded-xl border p-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-black">{admin.name}</p><p className="app-muted-text truncate text-xs">{admin.email}</p></div><Revoke id={admin.id} /></div>)}{assigned.length === 0 && <p className="app-muted-text rounded-xl border border-dashed p-4 text-center text-xs">暂未指定普通管理员。</p>}</div></section>; }
