"use client";

import { useActionState } from "react";
import { Save, Send } from "lucide-react";

import { initialHelpCenterActionState } from "@/app/dashboard/help/action-state";
import { createHelpArticleAction, updateHelpArticleAction } from "@/app/dashboard/help/actions";
import { HELP_ARTICLE_CATEGORY_LABELS, type HelpArticleCategory, type HelpArticleStatus } from "@/app/dashboard/help/config";

export type HelpArticleFormValue = { id: string; title: string; summary: string; content: string; category: HelpArticleCategory; status: HelpArticleStatus; is_featured: boolean; sort_order: number };

export function HelpArticleForm({ article }: { article?: HelpArticleFormValue }) {
  const action = article ? updateHelpArticleAction.bind(null, article.id) : createHelpArticleAction;
  const [state, formAction, pending] = useActionState(action, initialHelpCenterActionState);
  return <form action={formAction} className="space-y-4">{article && <input type="hidden" name="status" value={article.status} />}<label className="block text-xs font-black">文章标题<input name="title" required minLength={2} maxLength={120} defaultValue={article?.title} className="app-input mt-2 w-full rounded-xl border px-4 py-3 text-sm" /></label><label className="block text-xs font-black">简短摘要<textarea name="summary" maxLength={500} rows={2} defaultValue={article?.summary} className="app-input mt-2 w-full resize-y rounded-xl border px-4 py-3 text-sm leading-6" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-black">分类<select name="category" defaultValue={article?.category ?? "platform"} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm">{Object.entries(HELP_ARTICLE_CATEGORY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black">显示顺序<input type="number" name="sort_order" min={0} max={100000} defaultValue={article?.sort_order ?? 0} className="app-input mt-2 w-full rounded-xl border px-3 py-3 text-sm" /></label></div><label className="block text-xs font-black">文章正文<textarea name="content" required minLength={2} maxLength={10000} rows={article ? 8 : 10} defaultValue={article?.content} className="app-input mt-2 w-full resize-y rounded-xl border px-4 py-3 text-sm leading-7" /></label><label className="app-soft-card flex cursor-pointer items-center gap-3 rounded-xl border px-4 py-3 text-xs font-bold"><input type="checkbox" name="is_featured" defaultChecked={article?.is_featured} className="h-4 w-4" />设为推荐帮助</label>{state.message && <p className="rounded-xl px-3 py-2.5 text-xs font-bold" style={{ color: state.status === "error" ? "#c94f45" : "var(--app-success)", backgroundColor: state.status === "error" ? "#fff0ed" : "var(--app-success-soft)" }}>{state.message}</p>}<div className="flex flex-wrap gap-2">{article ? <button type="submit" disabled={pending} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black text-white disabled:opacity-50" style={{ backgroundColor: "var(--app-secondary)" }}><Save size={14} />{pending ? "正在保存…" : "保存修改"}</button> : <><button type="submit" name="intent" value="publish" disabled={pending} className="inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-black text-white disabled:opacity-50" style={{ backgroundColor: "var(--app-accent)" }}><Send size={15} />保存并发布</button><button type="submit" name="intent" value="draft" disabled={pending} className="app-soft-card inline-flex items-center gap-2 rounded-xl border px-5 py-3 text-sm font-black disabled:opacity-50"><Save size={15} />保存草稿</button></>}</div></form>;
}
