import Link from "next/link";
import { DashboardTitleWithHint } from "@/app/dashboard/DashboardTitleWithHint";
import { ArrowRight, BookOpenText, CheckCircle2, Clock3, Eye, HelpCircle, MessageCircleQuestion, ShieldCheck } from "lucide-react";

import { LocalDateTime } from "@/components/LocalDateTime";
import { getHelpCenterAccess } from "@/lib/help-center";
import { HelpArticleBrowser } from "./HelpArticleBrowser";
import { HelpTicketForm } from "./HelpTicketForm";
import { HELP_DATE_TIME_OPTIONS, HELP_TICKET_CATEGORY_LABELS, HELP_TICKET_STATUS_LABELS, type HelpArticleCategory, type HelpTicketCategory, type HelpTicketPriority, type HelpTicketStatus } from "./config";


type ArticleRow = { id: string; title: string; summary: string; content: string; category: HelpArticleCategory; is_featured: boolean };
type TicketRow = { id: string; subject: string; category: HelpTicketCategory; priority: HelpTicketPriority; status: HelpTicketStatus; resolution: string; created_at: string; updated_at: string };

export default async function HelpCenterPage() {
  const { supabase, user, role, canManage } = await getHelpCenterAccess();
  const [articlesResult, ticketsResult] = await Promise.all([
    supabase.from("help_articles").select("id,title,summary,content,category,is_featured").eq("status", "published").order("is_featured", { ascending: false }).order("sort_order", { ascending: true }).order("published_at", { ascending: false }),
    role === "student" ? supabase.from("help_tickets").select("id,subject,category,priority,status,resolution,created_at,updated_at").eq("user_id", user.id).order("updated_at", { ascending: false }) : Promise.resolve({ data: [] as TicketRow[], error: null }),
  ]);
  const articles = (articlesResult.data ?? []) as ArticleRow[];
  const tickets = (ticketsResult.data ?? []) as TicketRow[];
  const openCount = tickets.filter((item) => item.status === "open" || item.status === "in_progress").length;
  const solvedCount = tickets.filter((item) => item.status === "resolved" || item.status === "closed").length;

  return <div className="pb-12"><div className="mx-auto mt-5 w-full max-w-[1500px] space-y-5 px-4 sm:px-6 lg:px-8">{canManage && <div className="flex justify-end"><Link href="/dashboard/admin/help" className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-white" style={{ backgroundColor: "var(--support)" }}>进入帮助后台<ArrowRight size={15} aria-hidden="true" /></Link></div>}{canManage && <section className="app-card rounded-3xl border p-5 sm:p-6" style={{ background: "linear-gradient(125deg, var(--accent), var(--card), var(--status-success-surface))" }}><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_500px] xl:items-center"><div><span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold" style={{ color: "var(--status-success)", backgroundColor: "var(--status-success-surface)" }}><Eye size={14} aria-hidden="true" />学生端只读预览</span><DashboardTitleWithHint className="mt-3" title="检查学生能看到的帮助内容" description="学生可查看帮助文章、自己的求助进度和回复消息。" /></div><div className="dashboard-title-metrics">{[["帮助文章", articles.length, BookOpenText, "var(--primary)", "var(--accent)"], ["处理中", openCount, Clock3, "var(--status-warning)", "var(--status-warning-surface)"], ["已解决", solvedCount, CheckCircle2, "var(--status-success)", "var(--status-success-surface)" ]].map(([label, value, Icon, color, soft]) => { const MetricIcon = Icon as typeof HelpCircle; return <div key={String(label)} className="app-card rounded-2xl border p-4 text-center"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-xl" style={{ color: String(color), backgroundColor: String(soft) }}><MetricIcon size={17} aria-hidden="true" /></span><p className="mt-2 text-2xl font-bold">{String(value)}</p><p className="app-muted-text text-xs font-bold">{String(label)}</p></div>; })}</div></div></section>}
  {(articlesResult.error || ticketsResult.error) && <section role="alert" className="rounded-2xl border p-4 text-sm font-bold" style={{ color: "var(--status-warning)", backgroundColor: "var(--status-warning-surface)", borderColor: "var(--status-warning)" }}>帮助中心数据暂时无法读取，请稍后刷新重试。</section>}
  <HelpArticleBrowser articles={articles.map((item) => ({ ...item, isFeatured: item.is_featured }))} />
  {role === "student" && <div className="grid items-start gap-5 xl:grid-cols-[minmax(350px,0.78fr)_minmax(0,1.22fr)]"><HelpTicketForm /><section className="app-card rounded-3xl border p-4 sm:p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl" style={{ color: "var(--primary)", backgroundColor: "var(--accent)" }}><MessageCircleQuestion size={19} aria-hidden="true" /></span><h2 className="text-lg font-bold">我的求助记录</h2></div><div className="mt-5 divide-y app-divider">{tickets.map((ticket) => { const solved = ticket.status === "resolved" || ticket.status === "closed"; return <Link key={ticket.id} href={`/dashboard/help/tickets/${ticket.id}`} className="app-flat-row group block rounded-xl p-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)]"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full px-2.5 py-1 text-xs font-bold" style={{ color: "var(--support)", backgroundColor: "var(--support-surface)" }}>{HELP_TICKET_CATEGORY_LABELS[ticket.category]}</span><span className="rounded-full px-2.5 py-1 text-xs font-bold" style={{ color: solved ? "var(--status-success)" : "var(--status-warning)", backgroundColor: solved ? "var(--status-success-surface)" : "var(--status-warning-surface)" }}>{HELP_TICKET_STATUS_LABELS[ticket.status]}</span>{ticket.priority === "urgent" && <span className="text-xs font-bold text-[var(--destructive)]">紧急</span>}<ArrowRight className="ml-auto transition group-hover:translate-x-1" size={15} aria-hidden="true" /></div><h3 className="mt-3 text-sm font-bold">{ticket.subject}</h3><p className="app-muted-text mt-2 text-xs">更新于 <LocalDateTime value={ticket.updated_at} options={HELP_DATE_TIME_OPTIONS} /></p></Link>; })}{tickets.length === 0 && <div className="app-empty-state rounded-2xl p-6 text-center"><ShieldCheck className="mx-auto opacity-30" size={28} aria-hidden="true" /><p className="mt-3 text-sm font-bold">还没有求助记录</p><p className="app-muted-text mt-1 text-xs">提交后，处理进度会显示在这里。</p></div>}</div></section></div>}
  </div></div>;
}
