-- OID-independent application-facing schema inventory. No business table reads.
SET search_path = '';
WITH ns AS (SELECT oid FROM pg_namespace WHERE nspname IN
 ('public','private','recording_private','runtime_publish_private')),
rels AS (SELECT c.*, n.nspname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relnamespace IN (SELECT oid FROM ns)),
funcs AS (SELECT p.*,n.nspname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.pronamespace IN (SELECT oid FROM ns) AND p.prokind IN ('f','p'))
SELECT jsonb_build_object(
 'schemas',(SELECT jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',(SELECT array_agg(a::text ORDER BY a::text) FROM unnest(nspacl) a)) ORDER BY nspname) FROM pg_namespace WHERE oid IN (SELECT oid FROM ns)),
 'relations',(SELECT jsonb_agg(jsonb_build_object('schema',nspname,'name',relname,'kind',relkind,'owner',pg_get_userbyid(relowner),'rls',relrowsecurity,'forceRls',relforcerowsecurity,'persistence',relpersistence,'options',reloptions,'replicaIdentity',relreplident,'partition',pg_get_partkeydef(oid),'bound',pg_get_expr(relpartbound,oid),'acl',(SELECT array_agg(a::text ORDER BY a::text) FROM unnest(relacl) a)) ORDER BY nspname,relname) FROM rels WHERE relkind IN ('r','p','v','m','S','f')),
 'columns',(SELECT jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'number',a.attnum,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'collation',CASE WHEN a.attcollation=0 THEN NULL ELSE a.attcollation::regcollation::text END,'acl',(SELECT array_agg(x::text ORDER BY x::text) FROM unnest(a.attacl) x)) ORDER BY c.nspname,c.relname,a.attnum) FROM rels c JOIN pg_attribute a ON a.attrelid=c.oid LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum WHERE a.attnum>0 AND NOT a.attisdropped AND c.relkind IN ('r','p','v','m','f','c')),
 'types',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'category',t.typcategory,'base',format_type(t.typbasetype,t.typtypmod),'notNull',t.typnotnull,'default',t.typdefault,'enum',(SELECT jsonb_agg(e.enumlabel ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid=t.oid),'acl',(SELECT array_agg(a::text ORDER BY a::text) FROM unnest(t.typacl) a)) ORDER BY n.nspname,t.typname) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE t.typnamespace IN (SELECT oid FROM ns)),
 'constraints',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'typeName',t.typname,'name',con.conname,'kind',con.contype,'definition',pg_get_constraintdef(con.oid,false),'validated',con.convalidated,'deferrable',con.condeferrable,'deferred',con.condeferred) ORDER BY n.nspname,c.relname,t.typname,con.conname) FROM pg_constraint con JOIN pg_namespace n ON n.oid=con.connamespace LEFT JOIN pg_class c ON c.oid=con.conrelid LEFT JOIN pg_type t ON t.oid=con.contypid WHERE con.connamespace IN (SELECT oid FROM ns)),
 'indexes',(SELECT jsonb_agg(jsonb_build_object('schema',c.nspname,'table',c.relname,'name',ci.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready,'clustered',i.indisclustered) ORDER BY c.nspname,c.relname,ci.relname) FROM rels c JOIN pg_index i ON i.indrelid=c.oid JOIN pg_class ci ON ci.oid=i.indexrelid),
 'functions',(SELECT jsonb_agg(jsonb_build_object('schema',nspname,'name',proname,'arguments',pg_get_function_arguments(oid),'identityArguments',pg_get_function_identity_arguments(oid),'result',pg_get_function_result(oid),'definition',pg_get_functiondef(oid),'owner',pg_get_userbyid(proowner),'securityDefiner',prosecdef,'searchPathAndConfig',proconfig,'acl',(SELECT array_agg(a::text ORDER BY a::text) FROM unnest(proacl) a)) ORDER BY nspname,proname,pg_get_function_identity_arguments(oid)) FROM funcs),
 'triggers',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,false)) ORDER BY n.nspname,c.relname,t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE NOT t.tgisinternal AND (n.oid IN (SELECT oid FROM ns) OR n.nspname='auth' AND t.tgname IN ('on_auth_user_created','z_sync_auth_registration_metadata'))),
 'policies',(SELECT jsonb_agg(to_jsonb(p) ORDER BY schemaname,tablename,policyname) FROM pg_policies p WHERE schemaname IN ('public','private','recording_private','runtime_publish_private','storage','realtime')),
 'views',(SELECT jsonb_agg(jsonb_build_object('schema',nspname,'name',relname,'definition',pg_get_viewdef(oid,false)) ORDER BY nspname,relname) FROM rels WHERE relkind IN ('v','m')),
 'sequences',(SELECT jsonb_agg(jsonb_build_object('schema',c.nspname,'name',c.relname,'type',format_type(s.seqtypid,NULL),'start',s.seqstart,'increment',s.seqincrement,'max',s.seqmax,'min',s.seqmin,'cache',s.seqcache,'cycle',s.seqcycle) ORDER BY c.nspname,c.relname) FROM pg_sequence s JOIN rels c ON c.oid=s.seqrelid),
 'defaultGrants',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'role',pg_get_userbyid(d.defaclrole),'kind',d.defaclobjtype,'acl',(SELECT array_agg(a::text ORDER BY a::text) FROM unnest(d.defaclacl) a)) ORDER BY n.nspname,pg_get_userbyid(d.defaclrole),d.defaclobjtype) FROM pg_default_acl d JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE n.oid IN (SELECT oid FROM ns)),
 'eventTriggers',(SELECT jsonb_agg(jsonb_build_object('name',evtname,'owner',pg_get_userbyid(evtowner),'event',evtevent,'enabled',evtenabled,'tags',evttags,'function',evtfoid::regprocedure::text) ORDER BY evtname) FROM pg_event_trigger WHERE evtfoid IN (SELECT oid FROM funcs)),
 'inheritance',(SELECT jsonb_agg(jsonb_build_object('schema',c.nspname,'child',c.relname,'parent',i.inhparent::regclass::text,'seq',i.inhseqno) ORDER BY c.nspname,c.relname,i.inhseqno) FROM pg_inherits i JOIN rels c ON c.oid=i.inhrelid),
 'publicationMemberships',(SELECT jsonb_agg(to_jsonb(p) ORDER BY p.pubname,p.schemaname,p.tablename) FROM pg_publication_tables p WHERE p.schemaname IN ('public','private','recording_private','runtime_publish_private'))
);
