import os,sys,json,hashlib,configparser,subprocess,datetime,urllib.request
from pathlib import Path
os.umask(0o077);R=Path('/home/yangzhen/projects/my-lms-system');E=R/'docs/evidence/teaching-agent-stage-1f-r7c-b';DB=Path('/home/yangzhen/.config/uply-first-enable-20260910/db');C=json.loads((DB.parent/'runtime.json').read_text());start=datetime.datetime.now(datetime.timezone.utc);end=start+datetime.timedelta(minutes=30)
sha=lambda s:hashlib.sha256(s.encode()).hexdigest();digest=lambda v:sha(json.dumps(v,sort_keys=True,separators=(',',':')))
p=configparser.ConfigParser(interpolation=None);p.read(DB/'pg_service.conf');e=p['uply'];assert e['sslmode']=='verify-full' and e['sslrootcert']=='/connection/root.crt' and e['passfile']=='/connection/pgpass'
project=C['NEXT_PUBLIC_SUPABASE_URL'].split('//')[1].split('.')[0];assert project in e['host'] or project in e['user'];assert digest(project)=='cad8258f794d075042a59e5df2217f60173e29fbe15a2bf4b3324360d79df673';assert sha(C['NEXT_PUBLIC_SUPABASE_URL'].rstrip('/'))=='ff8db3ba3da8be9b994619fb66af48143c9ea9236e6454d2c59705d7b3279ea3'
def query(sql):
 a=['docker','run','--rm','--pull=never','--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--user',str(os.getuid())+':'+str(os.getgid()),'--network=host','-i','--mount',f'type=bind,source={DB},target=/connection,readonly','-e','PGSERVICEFILE=/connection/pg_service.conf','-e','PGOPTIONS=-c default_transaction_read_only=on','--entrypoint','psql','public.ecr.aws/supabase/postgres:17.6.1.159','-X','-qAt','-w','-v','ON_ERROR_STOP=1','service=uply']
 r=subprocess.run(a,input=sql.encode(),capture_output=True,timeout=45)
 if r.returncode:raise RuntimeError('READ_ONLY_QUERY_FAILED (credentials and stderr withheld)')
 rows=[json.loads(s) for s in r.stdout.decode().splitlines() if s.startswith('{') or s.startswith('[')];assert len(rows)==1;return rows[0]
def wrapped(sql):return query("BEGIN READ ONLY;SET LOCAL statement_timeout='15s';"+sql+";ROLLBACK;")
snapshot=query(Path('/tmp/r7cb-b2-approved-read.sql').read_text());assert snapshot['canonicalValid'] and not snapshot['actors'] and not snapshot['tenants']
meta=wrapped("SELECT json_build_object('postgres',current_setting('server_version'),'readOnly',current_setting('transaction_read_only'),'ledger',(SELECT count(*) FROM supabase_migrations.schema_migrations),'latest',(SELECT max(version) FROM supabase_migrations.schema_migrations),'agentRuns',(SELECT count(*) FROM public.agent_runs))")
tr=wrapped("SELECT coalesce(json_agg(json_build_object('table',n.nspname||'.'||cl.relname,'trigger',t.tgname,'definitionSha256',encode(sha256(convert_to(pg_get_triggerdef(t.oid),'UTF8')),'hex'),'function',p.oid::regprocedure::text,'functionSha256',encode(sha256(convert_to(pg_get_functiondef(p.oid),'UTF8')),'hex'),'enabled',t.tgenabled) ORDER BY n.nspname,cl.relname,t.tgname),'[]'::json) FROM pg_trigger t JOIN pg_class cl ON cl.oid=t.tgrelid JOIN pg_namespace n ON n.oid=cl.relnamespace JOIN pg_proc p ON p.oid=t.tgfoid WHERE NOT t.tgisinternal AND ((n.nspname='auth') OR (n.nspname='public' AND cl.relname IN ('profiles','tenants','tenant_memberships','user_permission_grants','account_management_audit_logs','tenant_provisioned_accounts')))")
prior=json.loads((E/'b2-auth-side-effect-map.before-initial-ban-workflow.json').read_text())['sources'];assert [{k:v for k,v in x.items() if k!='enabled'} for x in tr]==prior and all(x['enabled']=='O' for x in tr)
def get(url,headers):
 with urllib.request.urlopen(urllib.request.Request(url,headers=headers,method='GET'),timeout=20) as r:return json.load(r)
url=C['NEXT_PUBLIC_SUPABASE_URL'];health=get(url+'/auth/v1/health',{'apikey':C['NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY']});settings=get(url+'/auth/v1/settings',{'apikey':C['NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY']})
token=(Path.home()/'.supabase/access-token').read_text().strip();data=get('https://api.supabase.com/v1/projects/'+project+'/config/auth',{'Authorization':'Bearer '+token});safe={k:v for k,v in data.items() if isinstance(v,(bool,int,float)) and any(t in k for t in ['enable','disable','autoconfirm','confirm','otp','expiry','exp','rotation','refresh','session','password','rate_limit','audit'])}
for k in ['mailer_otp_length','mailer_otp_exp','password_min_length','password_required_characters','security_refresh_token_reuse_interval']:
 if k in data and isinstance(data[k],(str,int,bool)):safe[k]=data[k]
old=json.loads((E/'b2-workflow-auth-environment.json').read_text());authmatch=health==old['health']['data'] and settings.get('external',{})==old['externalProviders'] and safe==old['safeManagementConfig'];assert authmatch
lock=json.loads((E/'b2-workflow-source-lock.json').read_text())['newProductFiles'];assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in lock.items())
procs=json.loads(subprocess.check_output(['pm2','jlist']));app=next(x for x in procs if x['name']=='uply-first-enable');live=Path(app['pm2_env']['pm_cwd']);build=(live/'.next/BUILD_ID').read_text().strip();assert build=='f3AMbrTZfbg0_VWwnSE6i' and app['pm2_env']['status']=='online';assert meta['ledger']==458 and meta['latest']=='202609170001' and meta['postgres']=='17.6'
refs=(live/'.next/server/server-reference-manifest.json').read_text();routes=(live/'.next/server/app-paths-manifest.json').read_text();assert 'provisionDevelopmentExecutionAction' not in refs and 'development-execution' not in routes
claims=[]
for root in [Path('/home/yangzhen/operations/uply/teaching-agent'),Path('/home/yangzhen/.config/uply-first-enable-20260910')]:
 claims += [str(p) for p in root.rglob('development-domain-execution-v1.provision.jsonl')]
assert not claims
flag=C.get('TEACHING_AGENT_STUDENT_TRANSPORT_ENABLED') in (None,False,'false','0','');allow=all(C.get(k) in (None,'',[]) for k in ['TEACHING_AGENT_ALLOWED_TENANTS','TEACHING_AGENT_ALLOWED_COURSES','TEACHING_AGENT_ALLOWED_USERS']);assert flag and allow
out={'approval':'Approval B — APPROVED BY USER','preflightStartedAt':start.isoformat(),'maximumWindowEndsAt':end.isoformat(),'windowMinutes':30,'currentBuild':build,'pm2':'online',**meta,'sourceLock':'MATCH / 7 files','projectIdentitySha256':digest(project),'authApiOriginSha256':sha(url.rstrip('/')),'tls':'verify-full','canonicalValid':True,'B1':'COMPLETE','canonicalBinding':[1,1,1],'frozenContent':'UNCHANGED (same full-row frozen hashes in approved SQL)','actorCount':0,'tenantCount':0,'authVersion':health['version'],'authConfigProviders':'MATCH','triggerParity':'MATCH / '+str(len(tr)),'priorJournalClaimsFound':len(claims),'journalClaimCreated':False,'journalDirectoryProvisioned':False,'feature':'OFF','allowlists':'EMPTY','authenticatedProductionActionAvailable':False,'approvedDevelopmentCompositionInstalled':False,'ownerGuardInvoked':False,'status':'BLOCKED','blocker':'OWNER_AUTHENTICATED_DEVELOPMENT_PROVISIONING_ENTRYPOINT_UNAVAILABLE','mutationDispatches':0,'currentDbWrites':0,'attempt':0,'progress':0,'executionScope':'DISABLED','provider':0,'publish':0,'pins':0,'deploy':0,'R7D':'NOT READY','Stage1G':'NOT READY'}
(E/'b2-approved-fresh-preflight.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
