-- Unified permission center.
--
-- All application-level exception grants are stored in one auditable table.
-- Legacy per-module assignment tables are imported once and then frozen.
-- Application access and RLS helpers only read the unified grant table.

create table if not exists public.permission_grants (
  id bigint generated by default as identity primary key,
  scope_type text not null check (scope_type in ('platform', 'tenant')),
  tenant_id uuid references public.tenants(id) on delete cascade,
  subject_user_id uuid not null references public.profiles(id) on delete cascade,
  permission_key text not null check (permission_key in (
    'standard_question_bank.manage',
    'conversation_practice.manage',
    'grade_center.manage',
    'learning_records.manage',
    'document_reviews.manage',
    'visa_management.manage'
  )),
  granted_by uuid not null references public.profiles(id) on delete restrict,
  granted_at timestamptz not null default now(),
  revoked_by uuid references public.profiles(id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  check (
    (scope_type = 'platform' and tenant_id is null)
    or (scope_type = 'tenant' and tenant_id is not null)
  ),
  check (
    (revoked_at is null and revoked_by is null)
    or (revoked_at is not null and revoked_by is not null)
  )
);

create unique index if not exists permission_grants_active_platform_idx
  on public.permission_grants (subject_user_id, permission_key)
  where scope_type = 'platform' and tenant_id is null and revoked_at is null;

create unique index if not exists permission_grants_active_tenant_idx
  on public.permission_grants (tenant_id, subject_user_id, permission_key)
  where scope_type = 'tenant' and revoked_at is null;

create index if not exists permission_grants_subject_idx
  on public.permission_grants (subject_user_id, tenant_id, permission_key, revoked_at);

create table if not exists public.permission_grant_audit_logs (
  id bigint generated by default as identity primary key,
  permission_grant_id bigint references public.permission_grants(id) on delete set null,
  actor_id uuid references public.profiles(id) on delete set null,
  subject_user_id uuid not null,
  tenant_id uuid,
  permission_key text not null,
  action text not null check (action in ('granted', 'revoked')),
  created_at timestamptz not null default now()
);

create index if not exists permission_grant_audit_logs_created_idx
  on public.permission_grant_audit_logs (created_at desc);

alter table public.permission_grants enable row level security;
alter table public.permission_grant_audit_logs enable row level security;

drop policy if exists "permission grants visible to authorized viewers"
  on public.permission_grants;
create policy "permission grants visible to authorized viewers"
on public.permission_grants for select to authenticated
using (
  subject_user_id = (select auth.uid())
  or (select private.is_platform_owner())
  or exists (
    select 1
    from public.tenant_memberships as membership
    where membership.user_id = (select auth.uid())
      and membership.tenant_id = permission_grants.tenant_id
      and membership.status = 'active'
      and membership.role in ('tenant_super_admin', 'ceo')
  )
);

drop policy if exists "permission audit visible to platform owner"
  on public.permission_grant_audit_logs;
create policy "permission audit visible to platform owner"
on public.permission_grant_audit_logs for select to authenticated
using ((select private.is_platform_owner()));

revoke all on public.permission_grants from anon, authenticated;
revoke all on public.permission_grant_audit_logs from anon, authenticated;
grant select on public.permission_grants to authenticated;
grant select on public.permission_grant_audit_logs to authenticated;

create or replace function private.current_user_has_explicit_permission(
  requested_permission_key text,
  requested_tenant_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.permission_grants as permission_grant
    join public.profiles as profile
      on profile.id = permission_grant.subject_user_id
    where permission_grant.subject_user_id = (select auth.uid())
      and permission_grant.permission_key = requested_permission_key
      and permission_grant.revoked_at is null
      and coalesce(profile.status, 'active') = 'active'
      and (
        (requested_tenant_id is null
          and permission_grant.scope_type = 'platform'
          and permission_grant.tenant_id is null)
        or
        (requested_tenant_id is not null
          and permission_grant.scope_type = 'tenant'
          and permission_grant.tenant_id = requested_tenant_id)
      )
  );
$$;

revoke all on function private.current_user_has_explicit_permission(text, uuid) from public;
grant execute on function private.current_user_has_explicit_permission(text, uuid) to authenticated;

-- Move every business-table RLS helper onto the unified source of truth. This
-- removes the last runtime dependency on the per-module assignment tables.
create or replace function private.can_manage_standard_question_bank()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_platform_owner()
    or private.current_user_has_explicit_permission(
      'standard_question_bank.manage',
      null
    );
$$;

create or replace function public.current_user_can_manage_conversation_practice()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_active_account() and (
    public.current_profile_role() in ('tenant_super_admin', 'ceo')
    or (
      public.current_profile_role() = 'admin'
      and private.current_user_has_explicit_permission(
        'conversation_practice.manage',
        private.current_tenant_id()
      )
    )
  );
$$;

create or replace function public.current_user_can_manage_grade_center()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_active_account() and (
    public.current_profile_role() in ('tenant_super_admin', 'ceo')
    or (
      public.current_profile_role() = 'admin'
      and private.current_user_has_explicit_permission(
        'grade_center.manage',
        private.current_tenant_id()
      )
    )
  );
$$;

create or replace function public.current_user_can_manage_learning_records()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_active_account() and (
    public.current_profile_role() in ('tenant_super_admin', 'ceo')
    or (
      public.current_profile_role() = 'admin'
      and private.current_user_has_explicit_permission(
        'learning_records.manage',
        private.current_tenant_id()
      )
    )
  );
$$;

create or replace function public.current_user_can_manage_document_reviews()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_active_account() and (
    public.current_profile_role() in ('tenant_super_admin', 'ceo')
    or (
      public.current_profile_role() = 'admin'
      and private.current_user_has_explicit_permission(
        'document_reviews.manage',
        private.current_tenant_id()
      )
    )
  );
$$;

create or replace function public.current_user_can_manage_visas()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_active_account() and (
    public.current_profile_role() in ('tenant_super_admin', 'ceo')
    or (
      public.current_profile_role() = 'admin'
      and private.current_user_has_explicit_permission(
        'visa_management.manage',
        private.current_tenant_id()
      )
    )
  );
$$;

create or replace function public.set_user_permission_grant(
  requested_subject_user_id uuid,
  requested_permission_key text,
  requested_tenant_id uuid default null,
  requested_enabled boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  grant_id bigint;
  actor_id uuid := auth.uid();
begin
  if actor_id is null or not private.is_platform_owner() then
    raise exception '只有平台负责人可以修改统一权限';
  end if;

  if requested_permission_key not in (
    'standard_question_bank.manage',
    'conversation_practice.manage',
    'grade_center.manage',
    'learning_records.manage',
    'document_reviews.manage',
    'visa_management.manage'
  ) then
    raise exception '权限编号无效';
  end if;

  if requested_tenant_id is null then
    if requested_permission_key <> 'standard_question_bank.manage' then
      raise exception '该权限必须指定机构';
    end if;
    if not exists (
      select 1 from public.profiles as profile
      where profile.id = requested_subject_user_id
        and profile.global_role in ('platform_deputy', 'platform_admin')
        and coalesce(profile.status, 'active') = 'active'
    ) then
      raise exception '只能给正常的平台副负责人或平台管理员授权';
    end if;
  else
    if requested_permission_key = 'standard_question_bank.manage' then
      raise exception '标准题库权限只能在平台范围分配';
    end if;
    if not exists (
      select 1
      from public.tenant_memberships as membership
      join public.profiles as profile on profile.id = membership.user_id
      where membership.tenant_id = requested_tenant_id
        and membership.user_id = requested_subject_user_id
        and membership.role = 'admin'
        and membership.status = 'active'
        and coalesce(profile.status, 'active') = 'active'
    ) then
      raise exception '只能给当前机构状态正常的管理员授权';
    end if;
  end if;

  if requested_enabled then
    select permission_grant.id
      into grant_id
    from public.permission_grants as permission_grant
    where permission_grant.subject_user_id = requested_subject_user_id
      and permission_grant.permission_key = requested_permission_key
      and permission_grant.revoked_at is null
      and (
        (requested_tenant_id is null and permission_grant.scope_type = 'platform' and permission_grant.tenant_id is null)
        or (requested_tenant_id is not null and permission_grant.scope_type = 'tenant' and permission_grant.tenant_id = requested_tenant_id)
      )
    limit 1;

    if grant_id is null then
      insert into public.permission_grants (
        scope_type,
        tenant_id,
        subject_user_id,
        permission_key,
        granted_by
      ) values (
        case when requested_tenant_id is null then 'platform' else 'tenant' end,
        requested_tenant_id,
        requested_subject_user_id,
        requested_permission_key,
        actor_id
      ) returning id into grant_id;

      insert into public.permission_grant_audit_logs (
        permission_grant_id,
        actor_id,
        subject_user_id,
        tenant_id,
        permission_key,
        action
      ) values (
        grant_id,
        actor_id,
        requested_subject_user_id,
        requested_tenant_id,
        requested_permission_key,
        'granted'
      );
    end if;
  else
    update public.permission_grants
    set revoked_by = actor_id,
        revoked_at = now()
    where subject_user_id = requested_subject_user_id
      and permission_key = requested_permission_key
      and revoked_at is null
      and (
        (requested_tenant_id is null and scope_type = 'platform' and tenant_id is null)
        or (requested_tenant_id is not null and scope_type = 'tenant' and tenant_id = requested_tenant_id)
      )
    returning id into grant_id;

    if grant_id is not null then
      insert into public.permission_grant_audit_logs (
        permission_grant_id,
        actor_id,
        subject_user_id,
        tenant_id,
        permission_key,
        action
      ) values (
        grant_id,
        actor_id,
        requested_subject_user_id,
        requested_tenant_id,
        requested_permission_key,
        'revoked'
      );
    end if;
  end if;

  return grant_id;
end;
$$;

revoke all on function public.set_user_permission_grant(uuid, text, uuid, boolean) from public;
grant execute on function public.set_user_permission_grant(uuid, text, uuid, boolean) to authenticated;

-- Migrate every still-active grant into the unified table. Historical revoked
-- rows remain in the old tables and are not treated as active permissions.
do $$
declare
  mapping record;
begin
  for mapping in
    select * from (values
      ('conversation_practice_admin_assignments', 'conversation_practice.manage'),
      ('grade_center_admin_assignments', 'grade_center.manage'),
      ('learning_record_admin_assignments', 'learning_records.manage'),
      ('document_review_admin_assignments', 'document_reviews.manage'),
      ('visa_admin_assignments', 'visa_management.manage')
    ) as value(table_name, permission_key)
  loop
    if to_regclass('public.' || mapping.table_name) is not null then
      execute format(
        'insert into public.permission_grants (
           scope_type, tenant_id, subject_user_id, permission_key,
           granted_by, granted_at
         )
         select ''tenant'', tenant_id, admin_id, $1, granted_by, granted_at
         from public.%I as legacy
         where legacy.revoked_at is null
           and not exists (
             select 1 from public.permission_grants as existing
             where existing.scope_type = ''tenant''
               and existing.tenant_id = legacy.tenant_id
               and existing.subject_user_id = legacy.admin_id
               and existing.permission_key = $1
               and existing.revoked_at is null
           )',
        mapping.table_name
      ) using mapping.permission_key;
    end if;
  end loop;

  if to_regclass('public.question_bank_admin_assignments') is not null then
    insert into public.permission_grants (
      scope_type, tenant_id, subject_user_id, permission_key,
      granted_by, granted_at
    )
    select
      'platform', null, legacy.admin_id, 'standard_question_bank.manage',
      legacy.granted_by, legacy.granted_at
    from public.question_bank_admin_assignments as legacy
    where legacy.revoked_at is null
      and not exists (
        select 1 from public.permission_grants as existing
        where existing.scope_type = 'platform'
          and existing.tenant_id is null
          and existing.subject_user_id = legacy.admin_id
          and existing.permission_key = 'standard_question_bank.manage'
          and existing.revoked_at is null
      );
  end if;
end;
$$;

-- Retire every direct client-facing legacy assignment API. These historical
-- tables are frozen and no longer participate in any permission decision.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'conversation_practice_admin_assignments',
    'grade_center_admin_assignments',
    'learning_record_admin_assignments',
    'library_admin_assignments',
    'document_review_admin_assignments',
    'visa_admin_assignments',
    'question_bank_admin_assignments',
    'announcement_admin_assignments',
    'help_center_admin_assignments'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('revoke all on public.%I from anon, authenticated', table_name);
    end if;
  end loop;
end;
$$;

comment on table public.permission_grants is
  '统一账号例外授权；角色继承权限由应用权限目录定义。';
comment on table public.permission_grant_audit_logs is
  '统一权限中心的授权与收回审计记录。';
